.TH dlm_tool 8

.SH NAME
dlm_tool - A program to join and leave lockspaces and display dlm information

.SH SYNOPSIS
.B
dlm_tool
[\fIOPTIONS\fR]
<\fBjoin | leave | lockdump | deadlock_check\fP>
<\fBname\fP>

.SH DESCRIPTION

\fBdlm_tool\fP is a program used to join or leave dlm lockspaces, dump
dlm lock state, and initiate deadlock detection cycles.  The name of a
lockspace follows the subcommand.

.SH OPTIONS
.TP
\fB-m\fP
The permission mode (in octal) of the lockspace device created by join;
default 0600.
.TP
\fB-M\fP
Dump MSTCPY locks in addition to locks held by local processes.
.TP
\fB-d\fP <num>
Resource directory enabled (1) or disabled (0) during join; default 0.
.TP
\fB-h\fP
Help.  Print out the usage syntax.
.TP
\fB-V\fP
Print version information.

.SH SEE ALSO
libdlm(3)

