#!/bin/bash
##############################################################################
#
# COPYRIGHT (c) 2023 CSG SYSTEMS INTERNATIONAL, INC. AND/OR ITS AFFILIATES
# (CSG). ALL RIGHTS RESERVED.
#
# THIS SOFTWARE AND RELATED INFORMATION IS CONFIDENTIAL AND PROPRIETARY TO CSG
# AND MAY NOT BE DISCLOSED, COPIED, MODIFIED, OR OTHERWISE USED EXCEPT IN
# ACCORDANCE WITH THE LICENSE AGREEMENT ENTERED INTO WITH CSG. THIS INFORMATION
# IS PROTECTED BY INTERNATIONAL COPYRIGHT LAWS AND ANY UNAUTHORIZED USE THEREOF
# MAY VIOLATE COPYRIGHT, TRADEMARK, AND OTHER LAWS. ANY UNAUTHORIZED USE OF THIS
# SOFTWARE AND/OR INFORMATION WILL AUTOMATICALLY TERMINATE YOUR RIGHT TO USE
# THIS SOFTWARE AND/OR INFORMATION.
#
##############################################################################
#
# FILE:		/src/dcs/tools/src/usr_lib_ocf_resource.d_heartbeat_imemst.sh
#
# FUNCTION:	ImE Master RH PCS Heartbeat Agent - Online/Offline/Status script.
#
# AUTHOR:	Everett Bennett Jr, CSGI
#		(Last Edited by: $Author: dotev $)
#
# USAGE:	Invoked from RH PCS
#
# INPUTS:	n/a
#
##############################################################################
#ident: /usr/lib/ocf/resource.d/heartbeat/imemst
##############################################################################
#
#log
#       Add header, revision history, and SCR number	SCR 20231013-0001

#log
#
##############################################################################
###
###  Used for 2-Node or Better RH PCS Cluster
###
# Notes:    On all nodes in the cluster, copy this file to /usr/lib/ocf/resource.d/heartbeat/imemst .
#
#	cp -p ${CGI_ROOT}/tools/bin/usr_lib_ocf_resource.d_heartbeat_imemst.sh /usr/lib/ocf/resource.d/heartbeat/imemst
#	chown root:0 /usr/lib/ocf/resource.d/heartbeat/imemst
#	chmod 755:/usr/lib/ocf/resource.d/heartbeat/imemst
#
#
# Shell script to start/stop CGI master daemons with RH PCS.
#
#######################################################################

# Initialization:

if [ -z "${OCF_ROOT}" ]; then
	: ${OCF_ROOT=/usr/lib/ocf}
fi

: ${OCF_FUNCTIONS_DIR:=${OCF_ROOT}/lib/heartbeat}

. ${OCF_FUNCTIONS_DIR}/ocf-shellfuncs
. ${OCF_FUNCTIONS_DIR}/ocf-binaries
. ${OCF_FUNCTIONS_DIR}/ocf-returncodes
. ${OCF_FUNCTIONS_DIR}/ocf-directories
. ${OCF_FUNCTIONS_DIR}/ocf-rarun
. ${OCF_FUNCTIONS_DIR}/ocf-distro

#######################################################################
#
# Defaults
#
export IMEMST_imever_default="10.0"
export IMEMST_dcscf_default="/opt/dcs_10.0/files/cgi_products.sh.r8p2cl"
export IMEMST_appst_default="/opt/dcs_10.0/files/cgi_appst_enable_disable.sh"
export IMEMST_clname_default="r8p2cl"
export IMEMST_cgiuser_default="cgi"
export IMEMST_cgigrp_default="dev"
export IMEMST_cgiuid_default="29886"
export IMEMST_cgigid_default="257"
export IMEMST_cgihome_default="/home/cgi"
export IMEMST_cgimlog_default="20000000"
export IMEMST_cgitaskmlog_default="50000000"
export IMEMST_dbg_default="No"
export IMEMST_debug_default="No"
export IMEMST_api_delay_default="10"
export IMEMST_statuscnt_default="5"
export IMEMST_statusslp_default="12"
export IMEMST_statustimeout_default="60"

#######################################################################

function meta_data
{
	cat <<END
<?xml version="1.0"?>
<!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
<resource-agent name="imemst" version="1.0">
<version>1.0</version>

<longdesc lang="en">
Resource Agent for ImE Master Service
</longdesc>
<shortdesc lang="en">Resource Agent for ImE Master Service</shortdesc>

<parameters>

<parameter name="imever" unique="1" required="1">
<longdesc lang="en">
Valid IME Version
</longdesc>
<shortdesc lang="en">ImE Version</shortdesc>
<content type="string" default="${IMEMST_imever_default}" />
</parameter>

<parameter name="clname" unique="1" required="1">
<longdesc lang="en">
Valid PCS Cluster Name
</longdesc>
<shortdesc lang="en">PCS Cluster Name</shortdesc>
<content type="string" default="${IMEMST_clname_default}" />
</parameter>

<parameter name="dcscf" unique="1" required="1">
<longdesc lang="en">
ImE DCS_CONFIG_FILE
</longdesc>
<shortdesc lang="en">ImE dcscf</shortdesc>
<content type="string" default="${IMEMST_dcscf_default}" />
</parameter>

<parameter name="appst" unique="1">
<longdesc lang="en">
ImE Actiive-Passive Script
</longdesc>
<shortdesc lang="en">ImE Active-Passive Script</shortdesc>
<content type="string" default="${IMEMST_appst_default}" />
</parameter>

<parameter name="cgiuser" unique="1">
<longdesc lang="en">
ImE CGI User Name
</longdesc>
<shortdesc lang="en">ImE CGI User Name</shortdesc>
<content type="string" default="${IMEMST_cgiuser_default}" />
</parameter>

<parameter name="cgigrp" unique="1">
<longdesc lang="en">
ImE CGI Group Name
</longdesc>
<shortdesc lang="en">ImE CGI Group Name</shortdesc>
<content type="string" default="${IMEMST_cgigrp_default}" />
</parameter>

<parameter name="cgiuid" unique="1">
<longdesc lang="en">
ImE CGI UID
</longdesc>
<shortdesc lang="en">ImE CGI UID</shortdesc>
<content type="string" default="${IMEMST_cgiuid_default}" />
</parameter>

<parameter name="cgigid" unique="1">
<longdesc lang="en">
ImE CGI GID
</longdesc>
<shortdesc lang="en">ImE CGI GID</shortdesc>
<content type="string" default="${IMEMST_cgigid_default}" />
</parameter>

<parameter name="cgihome" unique="1">
<longdesc lang="en">
ImE CGI Home Directory
</longdesc>
<shortdesc lang="en">ImE CGI Home Directory</shortdesc>
<content type="string" default="${IMEMST_cgihome_default}" />
</parameter>

<parameter name="cgimlog" unique="1">
<longdesc lang="en">
Size of cgi_mlog file : cgi_mlog -s ${IMEMST_cgimlog}
</longdesc>
<shortdesc lang="en">Size of cgi_mlog file</shortdesc>
<content type="string" default="${IMEMST_cgimlog_default}" />
</parameter>

<parameter name="cgitaskmlog" unique="1">
<longdesc lang="en">
Size of Taskmanager mlog file.
</longdesc>
<shortdesc lang="en">Size of Taskmanager file</shortdesc>
<content type="string" default="${IMEMST_cgitaskmlog_default}" />
</parameter>

<parameter name="dbg" unique="1">
<longdesc lang="en">
Execute functions.
</longdesc>
<shortdesc lang="en">Execute functions</shortdesc>
<content type="string" default="${IMEMST_dbg_default}" />
</parameter>

<parameter name="debug" unique="1">
<longdesc lang="en">
Debug Option
</longdesc>
<shortdesc lang="en">Debug Option</shortdesc>
<content type="string" default="${IMEMST_debug_default}" />
</parameter>

<parameter name="statuscnt" unique="1">
<longdesc lang="en">
Number of sleep intervals to perform cgi_status before failing.
</longdesc>
<shortdesc lang="en">Number of sleep intervals to perform cgi_status before failing.</shortdesc>
<content type="string" default="${IMEMST_statuscnt_default}" />
</parameter>

<parameter name="api_delay" unique="1">
<longdesc lang="en">
Sleep delay added to start stop monitor.
</longdesc>
<shortdesc lang="en">Sleep delay added to start stop monitor.</shortdesc>
<content type="string" default="${IMEMST_api_delay_default}" />
</parameter>

<parameter name="statusslp" unique="1">
<longdesc lang="en">
Number of seconds to sleep per interval for cgi_status check.
</longdesc>
<shortdesc lang="en">Number of seconds to sleep per interval for cgi_status check.</shortdesc>
<content type="string" default="${IMEMST_statusslp_default}" />
</parameter>

<parameter name="statustimeout" unique="1">
<longdesc lang="en">
Number of seconds to exit a program. Useful for NFS situations.
</longdesc>
<shortdesc lang="en">Number of seconds to exit a program. Useful for NFS situtations.</shortdesc>
<content type="string" default="${IMEMST_statustimeout_default}" />
</parameter>

</parameters>

<actions>
<action name="start"        timeout="1200s" />
<action name="stop"         timeout="1200s" />
<action name="monitor"      timeout="300s" interval="300s" depth="0" />
<action name="migrate_to"   timeout="1200s" />
<action name="migrate_from" timeout="1200s" />
<action name="meta-data"    timeout="5s" />
<action name="validate"     timeout="30s" />
<action name="validate-all" timeout="30s" />
</actions>
</resource-agent>
END
}

function imemst_usage
{
	cat <<ENDusage
usage: $0 {start|stop|monitor|migrate_to|migrate_from|validate|validate-all|meta-data}

Expects to have a fully populated OCF RA-compliant environment set.

#	cp -p ${CGI_ROOT}/tools/bin/usr_lib_ocf_resource.d_heartbeat_imemst.sh /usr/lib/ocf/resource.d/heartbeat/imemst

#	chown root:0 /usr/lib/ocf/resource.d/heartbeat/imemst

#	chmod 755:/usr/lib/ocf/resource.d/heartbeat/imemst

	pcs resource create --group imemst imemst100 imemst imever=10.0 clname=r8p2cl dcscf=/opt/dcs_10.0/files/cgi_products.sh.R8P2CL appst=/opt/dcs_10.0/files/cgi_appst_enable_disable.sh cgiuser=cgi cgigrp=dev cgiuid=29886 cgigid=257 cgihome=/home/cgi cgimlog=20000000 cgitaskmlog=50000000 dbg=No debug=No api_delay=10 statuscnt=5 statusslp=12 statustimeout=60 op start timeout=1200s op stop timeout=1200s op monitor timeout=300s op migrate_from timeout=1200s op migrate_to timeout=1200s

	pcs resource create --group imemst imemst100 imemst imever=10.0 clname=r8p2cl dcscf=/opt/dcs_10.0/files/cgi_products.sh.R8P2CL

	pcs resource meta imemst100 failure-timeout=300s

	pcs resource meta imemst100 resource-stickiness=100

	pcs resource meta imemst100 migration-threshold=1


ENDusage
}

function imemst_dcscf
{
	ocf_log info "${0} : imemst_dcscf : . ${DCS_CONFIG_FILE} 2>/dev/null 1>/dev/null"
	# . ${DCS_CONFIG_FILE} 2>/dev/null 1>/dev/null
	. ${DCS_CONFIG_FILE}

	ocf_log info "${0} : imemst_dcscf : ImELoG : ${ImELoG}"

	if [ -f ${ImELoG} ]; then
		ocf_log info "${0} : imemst_dcscf : Found ImELoG : ${ImELoG}"
	else
		ocf_log info "${0} : imemst_dcscf : /usr/bin/touch ${ImELoG}"
		if [ "X${dbg}" == "XNo" ]; then
			/usr/bin/touch ${ImELoG}
		fi
		ocf_log info "${0} : imemst_dcscf : /usr/bin/chown ${IMEMST_cgiuser}:${IMEMST_cgigrp} ${ImELoG}"
		if [ "X${dbg}" == "XNo" ]; then
			/usr/bin/chown ${IMEMST_cgiuser}:${IMEMST_cgigrp} ${ImELoG}
		fi
		ocf_log info "${0} : imemst_dcscf : /usr/bin/chmod 0644 ${ImELoG}"
		if [ "X${dbg}" == "XNo" ]; then
			/usr/bin/chmod 0644 ${ImELoG}
		fi
	fi
}
function imelog_stamp
{
	DATE_STAMP=`date '+%b %e %X'`
	NAME_STAMP=`basename $0`
	TIME_STAMP="$DATE_STAMP $NAME_STAMP"

	ocf_log info "${0} : imemst_stamp : ${1} : NAME_STAMP=${NAME_STAMP} DATE_STAMP=${DATE_STAMP} TIME_STAMP=${TIME_STAMP}"

	ImELoG_Dir=`dirname ${ImELoG}`
	if [ -d ${ImELoG_Dir} ]
	then
		if [ -f ${ImELoG} ]
		then
			ocf_log info "${0} : imelog_stamp :  found ${ImELoG}"
		else
			ocf_log info "${0} : imelog_stamp :  touch ${ImELoG}; chown ${IMEMST_cgiuser}:${IMEMST_cgigrp} ${ImELoG}; chmod 644 ${ImELoG}"
			if [ "X${dbg}" == "XNo" ]; then
				touch ${ImELoG}; chown ${IMEMST_cgiuser}:${IMEMST_cgigrp} ${ImELoG}; chmod 644 ${ImELoG}
			fi
		fi
	else
		ocf_log error "${0} : imelog_stamp : ImELoG_Dir = ${ImELoG_Dir} Not Found"
		ocf_exit_reason "${ImELoG_Dir} Not Found"
	fi
	if [ -f ${ImELoG} ]
	then
		(
			echo "####"
			echo "${0} : imelog_stamp :  ${1} : NAME_STAMP=${NAME_STAMP} DATE_STAMP=${DATE_STAMP} TIME_STAMP=${TIME_STAMP}"
			echo "####"
		) 2>&1  >> ${ImELoG}
	fi
}
function imemst_start
{
	imemst_dcscf

	if [ -f /var/dcs_${IMEMST_imever}/db/dcs/cgi_status_freeze ]; then
		ocf_log info "${0} : imemst_start : /var/dcs_${IMEMST_imever}/db/dcs/cgi_status_freeze exists : return ${OCF_SUCCESS}"
		return ${OCF_SUCCESS}
	else
		imelog_stamp imemst_start

		ocf_log info "${0} : imemst_start : /bin/su ${IMEMST_cgiuser} -c \" . ${DCS_CONFIG_FILE} 2>/dev/null 1>/dev/null ; cgi_startup start\""
		if [ "X${dbg}" == "XNo" ]; then
			(
				echo "####"
				echo "/bin/su ${IMEMST_cgiuser} -c \" . ${DCS_CONFIG_FILE} 2>/dev/null 1>/dev/null ; cgi_startup start\""
				echo "####"
				/bin/su ${IMEMST_cgiuser} -c " . ${DCS_CONFIG_FILE} 2>/dev/null 1>/dev/null ; cgi_startup start"
				echo "####"
			) 2>&1  >> ${ImELoG}
		fi

		RET_START=$?
		ocf_log info "${0} : imemst_start : RET_START ${RET_START} ; /bin/sleep ${IMEMST_api_delay}"
		if [ "X${dbg}" == "XNo" ]; then
			/bin/sleep ${IMEMST_api_delay}
		fi
	fi

	# Check to see if this is an active/passive configuration
	# cp -p ${CGI_ROOT}/tools/bin/cgi_appst_enable_disable.sh ${CGI_ROOT}/files/cgi_appst_enable_disable.sh
	#	
	if [ -f ${IMEMST_appst} ]; then
		ocf_log info "${0} : imemst_start : /bin/su ${IMEMST_cgiuser} -c \" . ${DCS_CONFIG_FILE} 2>/dev/null 1>/dev/null ; ${IMEMST_appst}\""
		if [ "X${dbg}" == "XNo" ]; then
			(
				echo "####"
				echo "/bin/su ${IMEMST_cgiuser} -c \" . ${DCS_CONFIG_FILE} 2>/dev/null 1>/dev/null ; ${IMEMST_appst}\""
				echo "####"
				/bin/su ${IMEMST_cgiuser} -c " . ${DCS_CONFIG_FILE} 2>/dev/null 1>/dev/null ; ${IMEMST_appst}"
				echo "####"
			) 2>&1  >> ${ImELoG}
		fi
	fi

	ocf_log info "${0} : imemst_start : /bin/sleep ${IMEMST_api_delay}"
	if [ "X${dbg}" == "XNo" ]; then
		/bin/sleep ${IMEMST_api_delay}
	fi

	ocf_log info "${0} : imemst_start : /bin/su ${IMEMST_cgiuser} -c \" . ${DCS_CONFIG_FILE} 2>/dev/null 1>/dev/null ; cgi_status --verbose\""
	if [ "X${dbg}" == "XNo" ]; then
		(
			echo "####"
			echo "/bin/su ${IMEMST_cgiuser} -c \" . ${DCS_CONFIG_FILE} 2>/dev/null 1>/dev/null ; cgi_status --verbose\""
			echo "####"
			/bin/su ${IMEMST_cgiuser} -c " . ${DCS_CONFIG_FILE} 2>/dev/null 1>/dev/null ; cgi_status --verbose"
			echo "####"
		) 2>&1  >> ${ImELoG}
	fi

	if [ "X${RET_START}" == "X${OCF_SUCCESS}" ]; then
		ocf_log info "${0} : imemst_start : RET_START ${RET_START} : return OCF_SUCCESS ${OCF_SUCCESS}"
		ocf_log info "${0} : imemst_start : imemst has been successfully started"
		return ${OCF_SUCCESS}
	else
		ocf_log error "${0} : imemst_start : RET_START ${RET_START}: OCF_NOT_RUNNING ${OCF_NOT_RUNNING}"
		return ${OCF_NOT_RUNNING}
	fi
}
function imemst_stop
{
	imemst_dcscf

	imelog_stamp imemst_stop

	if [ -f /var/dcs_${IMEMST_imever}/db/dcs/cgi_status_freeze ]; then
		ocf_log info "${0} : imemst_stop : /var/dcs_${IMEMST_imever}/db/dcs/cgi_status_freeze exists : return ${OCF_SUCCESS}"
		return $OCF_SUCCESS
	else
		ocf_log info "${0} : imemst_stop : /bin/su ${IMEMST_cgiuser} -c \" . ${DCS_CONFIG_FILE} 2>/dev/null 1>/dev/null ; cgi_startup stop\""
		if [ "X${dbg}" == "XNo" ]; then
			(
				echo "####"
				echo "/bin/su ${IMEMST_cgiuser} -c \" . ${DCS_CONFIG_FILE} 2>/dev/null 1>/dev/null ; cgi_startup stop\""
				echo "####"
				/bin/su ${IMEMST_cgiuser} -c " . ${DCS_CONFIG_FILE} 2>/dev/null 1>/dev/null ; cgi_startup stop"
				echo "####"
			) 2>&1  >> ${ImELoG}
		fi

		RET_STOP1=$?
		ocf_log info "${0} : imemst_stop : RET_STOP1 ${RET_STOP1}"

		ocf_log info "${0} : imemst_stop : /bin/su ${IMEMST_cgiuser} -c \" . ${DCS_CONFIG_FILE} 2>/dev/null 1>/dev/null ; cgi_system_startup stop\""
		if [ "X${dbg}" == "XNo" ]; then
			(
				echo "####"
				echo "/bin/su ${IMEMST_cgiuser} -c \" . ${DCS_CONFIG_FILE} 2>/dev/null 1>/dev/null ; cgi_system_startup stop\""
				echo "####"
				/bin/su ${IMEMST_cgiuser} -c " . ${DCS_CONFIG_FILE} 2>/dev/null 1>/dev/null ; cgi_system_startup stop"
				echo "####"
			) 2>&1  >> ${ImELoG}
		fi

		RET_STOP2=$?
		ocf_log info "${0} : imemst_stop : RET_STOP2 ${RET_STOP2}"

		if [ "X${RET_MONITOR}" != "X0" -o "X${IMEMST_debug}" = "XYes" ]; then
			ocf_log info "${0} : imemst_stop : /bin/su ${IMEMST_cgiuser} -c \" . ${DCS_CONFIG_FILE} 2>/dev/null 1>/dev/null ; cgi_status --verbose\""
			if [ "X${dbg}" == "XNo" ]; then
				(
					echo "####"
					echo "/bin/su ${IMEMST_cgiuser} -c \" . ${DCS_CONFIG_FILE} 2>/dev/null 1>/dev/null ; cgi_status --verbose\""
					echo "####"
					/bin/su ${IMEMST_cgiuser} -c " . ${DCS_CONFIG_FILE} 2>/dev/null 1>/dev/null ; cgi_status --verbose"
					echo "####"
				) 2>&1  >> ${ImELoG}
			fi
		fi
	fi
	# delay to avoid sending request too fast
	ocf_log info "${0} : imemst_stop : sleep ${IMEMST_api_delay}"
	if [ "X${dbg}" == "XNo" ]; then
		sleep ${IMEMST_api_delay}
	fi

	if [ "X${RET_STOP1}" == "X0" -a "X${RET_STOP2}" == "X0" ]
	then
		ocf_log info "${0} : imemst_stop : imemst has been successfully stopped : OCF_SUCCESS=${OCF_SUCCESS}"
		return ${OCF_SUCCESS}
	else
		ocf_log error "${0} : imemst_stop : RET_STOP1=${RET_STOP1} : RET_STOP2=${RET_STOP2} : OCF_NOT_RUNNING ${OCF_NOT_RUNNING}"
		return ${OCF_NOT_RUNNING}
	fi

}

function imemst_monitor
{
	imemst_dcscf

	imelog_stamp imemst_monitor

	if [ "X${IMEMST_debug}" = "XYes" ]; then
		ocf_log info "OCF_RESKEY_dcscf  = ${OCF_RESKEY_dcscf} IMEMST_dcscf_default = ${IMEMST_dcscf_default}"
		ocf_log info "OCF_RESKEY_appst  = ${OCF_RESKEY_appst} IMEMST_appst_default = ${IMEMST_appst_default}"
		ocf_log info "OCF_RESKEY_imever = ${OCF_RESKEY_imever} IMEMST_imever_default = ${IMEMST_imever_default}"
		ocf_log info "OCF_RESKEY_clname = ${OCF_RESKEY_clname} IMEMST_clname_default = ${IMEMST_clname_default}"
		ocf_log info "OCF_RESKEY_cgiuser = ${OCF_RESKEY_cgiuser} IMEMST_cgiuser_default = ${IMEMST_cgiuser_default}"
		ocf_log info "OCF_RESKEY_cgigrp = ${OCF_RESKEY_cgigrp} IMEMST_cgigrp_default = ${IMEMST_cgigrp_default}"
		ocf_log info "OCF_RESKEY_cgiuid = ${OCF_RESKEY_cgiuid} IMEMST_cgiuid_default = ${IMEMST_cgiuid_default}"
		ocf_log info "OCF_RESKEY_cgihome = ${OCF_RESKEY_cgihome} IMEMST_cgihome_default = ${IMEMST_cgihome_default}"
		ocf_log info "OCF_RESKEY_cgimlog = ${OCF_RESKEY_cgimlog} IMEMST_cgimlog_default = ${IMEMST_cgimlog_default}"
		ocf_log info "OCF_RESKEY_cgitaskmlog = ${OCF_RESKEY_cgitaskmlog} IMEMST_cgitaskmlog_default = ${IMEMST_cgitaskmlog_default}"
		ocf_log info "OCF_RESKEY_dbg = ${OCF_RESKEY_dbg} IMEMST_dbg_default = ${IMEMST_dbg_default}"
		ocf_log info "OCF_RESKEY_debug = ${OCF_RESKEY_debug} IMEMST_debug_default = ${IMEMST_debug_default}"
		ocf_log info "OCF_RESKEY_api_delay = ${OCF_RESKEY_api_delay} IMEMST_api_delay_default = ${IMEMST_api_delay_default}"
		ocf_log info "OCF_RESKEY_statuscnt = ${OCF_RESKEY_statuscnt} IMEMST_statuscnt_default = ${IMEMST_statuscnt_default}"
		ocf_log info "OCF_RESKEY_statusslp = ${OCF_RESKEY_statusslp} IMEMST_statusslp_default = ${IMEMST_statusslp_default}"
		ocf_log info "OCF_RESKEY_statustimeout = ${OCF_RESKEY_statustimeout} IMEMST_statustimeout_default = ${IMEMST_statustimeout_default}"
	fi

	get_os_ver
	ocf_log info "${0} : imemst_monitor : get_os_ver : OS ${OS} : VER ${VER}"

	# Monitor _MUST!_ differentiate correctly between running
	# (SUCCESS), failed (ERROR) or _cleanly_ stopped (NOT RUNNING).
	# That is THREE states, not just yes/no.
	
	# if ! ocf_is_probe && [ "${__OCF_ACTION}" = "monitor" ]; then
	# 	# set exit string only when NOT_RUNNING occurs during an actual monitor operation.
	# 	ocf_log error "${0} : imemst_monitor : OCF_NOT_RUNNING ${OCF_NOT_RUNNING} - No process state file found"
	# 	ocf_exit_reason "No process state file found"
	# 	return ${OCF_NOT_RUNNING}
	# fi

	if [ -f /var/dcs_${IMEMST_imever}/db/dcs/cgi_status_freeze ]; then
		ocf_log info "${0} : imemst_monitor : /var/dcs_${IMEMST_imever}/db/dcs/cgi_status_freeze exists"
		if [ "X${IMEMST_debug}" = "XYes" ]; then
			ocf_log info "${0} : imemst_monitor : /usr/bin/pgrep -G ${IMEMST_cgigid} -U ${IMEMST_cgiuser} -fla"
			if [ "X${dbg}" == "XNo" ]; then
				/usr/bin/pgrep -G ${IMEMST_cgigid} -U ${IMEMST_cgiuser} -fla
			fi
		fi
		return ${OCF_SUCCESS}
	else
		IMEMST_statuscnt_CNT=0
		while true
		do
			IMEMST_statuscnt_CNT=`expr ${IMEMST_statuscnt_CNT} + 1`
			if [ "X${IMEMST_debug}" = "XYes" ]; then
				ocf_log info "${0} : imemst_monitor : /bin/su ${IMEMST_cgiuser} -c \" . ${DCS_CONFIG_FILE} 2>/dev/null 1>/dev/null; cgi_status --verbose\""
				if [ "X${dbg}" == "XNo" ]; then
					(
						echo "####"
						echo "/bin/su ${IMEMST_cgiuser} -c \" . ${DCS_CONFIG_FILE} 2>/dev/null 1>/dev/null; cgi_status --verbose\""
						echo "####"
						/bin/su ${IMEMST_cgiuser} -c " . ${DCS_CONFIG_FILE} 2>/dev/null 1>/dev/null; cgi_status --verbose"
						echo "####"
					) 2>&1  >> ${ImELoG}
				fi
				ocf_log info "${0} : imemst_monitor : /bin/su ${IMEMST_cgiuser} -c \" . ${DCS_CONFIG_FILE} 2>/dev/null 1>/dev/null; cgi_status --monitor\""
				if [ "X${dbg}" == "XNo" ]; then
					(
						echo "####"
						echo "/bin/su ${IMEMST_cgiuser} -c \" . ${DCS_CONFIG_FILE} 2>/dev/null 1>/dev/null; cgi_status --monitor\""
						echo "####"
						/bin/su ${IMEMST_cgiuser} -c " . ${DCS_CONFIG_FILE} 2>/dev/null 1>/dev/null; cgi_status --monitor"
						echo "####"
					) 2>&1  >> ${ImELoG}
				fi
			fi
			ocf_log info "${0} : imemst_monitor : /bin/su ${IMEMST_cgiuser} -c \" . ${DCS_CONFIG_FILE} 2>/dev/null 1>/dev/null; cgi_status --monitor\""
			if [ "X${dbg}" == "XNo" ]; then
				(
					echo "####"
					echo "/bin/su ${IMEMST_cgiuser} -c \" . ${DCS_CONFIG_FILE} 2>/dev/null 1>/dev/null; cgi_status --monitor\""
					echo "####"
					/bin/su ${IMEMST_cgiuser} -c " . ${DCS_CONFIG_FILE} 2>/dev/null 1>/dev/null; cgi_status --monitor"
					echo "####"
				) 2>&1  >> ${ImELoG}
			fi
			RET_MONITOR=${?}
			ocf_log info "${0} : imemst_monitor : ${0}: RET_MONITOR=${RET_MONITOR}"
	
			# Normally, this will break the first time cgi_status --monitor is used.
			if [ "X${RET_MONITOR}" = "X0" ]; then
				break
			fi

			# If we have checked IMEMST_statuscnt_CNT times, then break out of loop.
			if [ "X${IMEMST_statuscnt_CNT}" = "X${IMEMST_statuscnt}" ]; then
				ocf_log info "${0} : imemst_monitor : IMEMST_statuscnt_CNT ${IMEMST_statuscnt_CNT}"
				break
			fi
			ocf_log info "${0} : imemst_monitor : sleep ${IMEMST_statusslp}"
			if [ "X${dbg}" == "XNo" ]; then
				sleep ${IMEMST_statusslp}
			fi
		done
		# If RET_MONITOR is not good, X0, then list some debug info, etc.
		if [ "X${RET_MONITOR}" != "X0" -o "X${IMEMST_debug}" = "XYes" ]; then
			ocf_log info "${0} : imemst_monitor : /bin/su ${IMEMST_cgiuser} -c \" . ${DCS_CONFIG_FILE} 2>/dev/null 1>/dev/null; cgi_status --verbose\""
			if [ "X${dbg}" == "XNo" ]; then
				(
					echo "####"
					echo "/bin/su ${IMEMST_cgiuser} -c \" . ${DCS_CONFIG_FILE} 2>/dev/null 1>/dev/null; cgi_status --verbose\""
					echo "####"
					/bin/su ${IMEMST_cgiuser} -c " . ${DCS_CONFIG_FILE} 2>/dev/null 1>/dev/null; cgi_status --verbose"
					echo "####"
				) 2>&1  >> ${ImELoG}
			fi
			ocf_log info "${0} : imemst_monitor : /usr/bin/pgrep -G ${IMEMST_cgigid} -U ${IMEMST_cgiuser} -fla"
			if [ "X${dbg}" == "XNo" ]; then
				/usr/bin/pgrep -G ${IMEMST_cgigid} -U ${IMEMST_cgiuser} -fla
			fi
			ocf_log info "${0} : imemst_monitor : /usr/bin/ps -fu ${IMEMST_cgiuser}"
			if [ "X${dbg}" == "XNo" ]; then
				/usr/bin/ps -fu ${IMEMST_cgiuser}
			fi
			ocf_log info "${0} : imemst_monitor : /usr/bin/ps -eaf"
			if [ "X${dbg}" == "XNo" ]; then
				/usr/bin/ps -eaf
			fi
	
			j="${DCS_INPUTBIN}/dcs_event_mgr"
			ocf_log info "${0} : imemst_monitor : /usr/bin/pgrep -G ${IMEMST_cgigid} -U ${IMEMST_cgiuser} -f \"^${j}\" 2>/dev/null 1>/dev/null"
			/usr/bin/pgrep -G ${IMEMST_cgigid} -U ${IMEMST_cgiuser} -f "^${j}" 2>/dev/null 1>/dev/null
			PGRPSTAT1=${?}
			ocf_log info "${0} : imemst_monitor : PGRPSTAT1 ${PGRPSTAT1} : /usr/bin/pgrep -G ${IMEMST_cgigid} -U ${IMEMST_cgiuser} -f \"^${j}\""
		fi
	fi
	if [ "X${RET_MONITOR}" == "X0" ]; then
		ocf_log info "${0} : imemst_monitor : RET_MONITOR=${RET_MONITOR} : OCF_SUCCESS ${OCF_SUCCESS}"
		return ${OCF_SUCCESS}
	else
		ocf_log info "${0} : imemst_monitor : RET_MONITOR=${RET_MONITOR} : OCF_NOT_RUNNING ${OCF_NOT_RUNNING}"
		return ${OCF_NOT_RUNNING}
	fi
}

function imemst_validate
{
	if [ -f ${IMEMST_dcscf} ]; then
		ocf_log info "${0} : imemst_validate : Found DCS_CONFIG_FILE : ${IMEMST_dcscf}"
	else
		ocf_log error "${0} : imemst_validate : ${IMEMST_dcscf}"
	fi

	if [ -z "${IMEMST_dcscf}" ]; then
		ocf_exit_reason "${0} : imemst_validate : dcscf parameter not set"
		return ${OCF_ERR_CONFIGURED}
	fi
	if [ -z "${IMEMST_imever}" ]; then
		ocf_exit_reason "${0} : imemst_validate : imever parameter not set"
		return ${OCF_ERR_CONFIGURED}
	fi
	if [ -z "${IMEMST_clname}" ]; then
		ocf_exit_reason "${0} : imemst_validate : clname parameter not set"
		return ${OCF_ERR_CONFIGURED}
	fi

	if [ -d /opt/dcs_${IMEMST_imever}/usr/local ]; then
		export IMEMST_ODULPATH=/opt/dcs_${IMEMST_imever}/usr/local
	elif [ -d /opt/dcs/usr/local ]; then
		export IMEMST_ODULPATH=/opt/dcs/usr/local
	else
		ocf_exit_reason "${0} : imemst_validate : IME ODULPATH Not Found"
		return ${OCF_ERR_CONFIGURED}
	fi

	return ${OCF_SUCCESS}
}

if [ -z "${OCF_RESKEY_dcscf}" ]; then
	export IMEMST_dcscf=${IMEMST_dcscf_default}
	export DCS_CONFIG_FILE=${IMEMST_dcscf_default}
else
	export IMEMST_dcscf=${OCF_RESKEY_dcscf}
	export DCS_CONFIG_FILE=${OCF_RESKEY_dcscf}
fi

if [ -z "${OCF_RESKEY_appst}" ]; then
	export IMEMST_appst=${IMEMST_appst_default}
else
	export IMEMST_appst=${OCF_RESKEY_appst}
fi

if [ -z "${OCF_RESKEY_imever}" ]; then
	export IMEMST_imever=${IMEMST_imever_default}
	export ImELoG=/var/dcs_${IMEMST_imever_default}/mlog/cgi_rh_pcs_mst.log
else
	export IMEMST_imever=${OCF_RESKEY_imever}
	export ImELoG=/var/dcs_${OCF_RESKEY_imever}/mlog/cgi_rh_pcs_mst.log
fi

export IMEMST_ODULPATH=unknown
if [ -d /opt/dcs_${IMEMST_imever}/usr/local ]; then
	export IMEMST_ODULPATH=/opt/dcs_${IMEMST_imever}/usr/local
elif [ -d /opt/dcs/usr/local ]; then
	export IMEMST_ODULPATH=/opt/dcs/usr/local
fi

if [ -z "${OCF_RESKEY_clname}" ]; then
	export IMEMST_clname=${IMEMST_clname_default}
else
	export IMEMST_clname=${OCF_RESKEY_clname}
fi

if [ -z "${OCF_RESKEY_cgiuser}" ]; then
	export IMEMST_cgiuser=${IMEMST_cgiuser_default}
else
	export IMEMST_cgiuser=${OCF_RESKEY_cgiuser}
fi

if [ -z "${OCF_RESKEY_cgigrp}" ]; then
	export IMEMST_cgigrp=${IMEMST_cgigrp_default}
else
	export IMEMST_cgigrp=${OCF_RESKEY_cgigrp}
fi

if [ -z "${OCF_RESKEY_cgiuid}" ]; then
	export IMEMST_cgiuid=${IMEMST_cgiuid_default}
else
	export IMEMST_cgiuid=${OCF_RESKEY_cgiuid}
fi

if [ -z "${OCF_RESKEY_cgigid}" ]; then
	export IMEMST_cgigid=${IMEMST_cgigid_default}
else
	export IMEMST_cgigid=${OCF_RESKEY_cgigid}
fi

if [ -z "${OCF_RESKEY_cgihome}" ]; then
	export IMEMST_cgihome=${IMEMST_cgihome_default}
else
	export IMEMST_cgihome=${OCF_RESKEY_cgihome}
fi

if [ -z "${OCF_RESKEY_cgimlog}" ]; then
	export IMEMST_cgimlog=${IMEMST_cgimlog_default}
else
	export IMEMST_cgimlog=${OCF_RESKEY_cgimlog}
fi

if [ -z "${OCF_RESKEY_cgitaskmlog}" ]; then
	export IMEMST_cgitaskmlog=${IMEMST_cgitaskmlog_default}
else
	export IMEMST_cgitaskmlog=${OCF_RESKEY_cgitaskmlog}
fi

if [ -z "${OCF_RESKEY_dbg}" ]; then
	export IMEMST_dbg=${IMEMST_dbg_default}
	export dbg=${IMEMST_dbg}
else
	export IMEMST_dbg=${OCF_RESKEY_dbg}
	export dbg=${OCF_RESKEY_dbg}
fi

if [ -z "${OCF_RESKEY_debug}" ]; then
	export IMEMST_debug=${IMEMST_debug_default}
else
	export IMEMST_debug=${OCF_RESKEY_debug}
fi

if [ -z "${OCF_RESKEY_api_delay}" ]; then
	export IMEMST_api_delay=${IMEMST_api_delay_default}
else
	export IMEMST_api_delay=${OCF_RESKEY_api_delay}
fi

if [ -z "${OCF_RESKEY_statuscnt}" ]; then
	export IMEMST_statuscnt=${IMEMST_statuscnt_default}
else
	export IMEMST_statuscnt=${OCF_RESKEY_statuscnt}
fi

if [ -z "${OCF_RESKEY_statusslp}" ]; then
	export IMEMST_statusslp=${IMEMST_statusslp_default}
else
	export IMEMST_statusslp=${OCF_RESKEY_statusslp}
fi

if [ -z "${OCF_RESKEY_statustimeout}" ]; then
	export IMEMST_statustimeout=${IMEMST_statustimeout_default}
else
	export IMEMST_statustimeout=${OCF_RESKEY_statustimeout}
fi

export __OCF_ACTION=${1}

# if [ ${#} -eq 2 ]
# then
	# export dbg=${2}
# fi

ocf_log info "__OCF_ACTION : ${__OCF_ACTION}"
ocf_log info "dbg : ${dbg}"

case ${__OCF_ACTION} in
	meta-data)
		meta_data
		exit ${OCF_SUCCESS}
	;;
esac

case ${__OCF_ACTION} in
	start)
		imemst_validate
		imemst_start
	;;
	stop)
		imemst_stop
	;;
	monitor)
		imemst_monitor
	;;
	migrate_to)
		ocf_log info "${0} : migrate_to : Migrating ${OCF_RESOURCE_INSTANCE} to ${OCF_RESKEY_CRM_meta_migrate_target}."
		imemst_stop
	    ;;
	migrate_from)
		ocf_log info "${0} : migrate_from : Migrating ${OCF_RESOURCE_INSTANCE} from ${OCF_RESKEY_CRM_meta_migrate_source}."
		imemst_start
	;;
	reload)
		ocf_log info "${0} : reload : Reloading ${OCF_RESOURCE_INSTANCE} ..."
	;;
	validate|validate-all)
		imemst_validate
	;;
	usage|help)
		imemst_usage
		exit ${OCF_SUCCESS}
	;;
	*)
		imemst_usage
		exit ${OCF_ERR_UNIMPLEMENTED}
	;;
esac

rc=$?
ocf_log debug "${0} : ImEMsT : ${OCF_RESOURCE_INSTANCE} ${__OCF_ACTION} : $rc"
exit $rc
