.TH gfs 8

.SH NAME
gfs \- GFS reference guide

.SH SYNOPSIS
Overview of manpages and their locations

.SH DESCRIPTION
The GFS documentation has been split into a number of sections.  Please
refer to the table below to determine which man page coincides with the
command/feature you are looking for.
.TP 16
gfs
GFS overview (this man page)
.TP
gfs_mount
Mounting a GFS file system
.TP
gfs_fsck
The GFS file system checker
.TP
gfs_grow
Growing a GFS file system
.TP
gfs_jadd
Adding a journal to a GFS file system
.TP
gfs_mkfs
Make a GFS file system
.TP
gfs_quota
Manipulate GFS disk quotas 
.TP
gfs_tool
Tool to manipulate a GFS file system

