.TH "cluarp" "8" "Jan 2005" "" "Red Hat Cluster Suite Internal Commands"
.SH "NAME"
cluarp \- Send a gratuitous ARP
.SH "WARNING"
Use of this command can cause the cluster to malfunction.  Do not run this
without instructions from Red Hat Support.
.SH "DESCRIPTION"
.PP 
The
.B cluarp
command is an internal command used to broadcast new ARP information when
a service IP address is configured by the Service Manager.

.SH "SEE ALSO"
arp(8)
