.TH "clubufflush" "8" "Jan 2005" "" "Red Hat Cluster Suite Internal Commands"
.SH "NAME"
clubufflush \- Flush buffers on a service's file system.

.SH "DESCRIPTION"
.PP 
The
.B clubufflush
command is an internal command used to synchronize buffers to disk
prior to stopping a clustered service.

.SH "SEE ALSO"
sync(1), sync(2), fsync(2), fdatasync(2)
