.TH "clunfsops" "8" "Jan 2005" "" "Red Hat Cluster Suite Internal Commands"
.SH "NAME"
clunfsops \- Manipulate NFS
.SH "WARNING"
Use of this command can cause the cluster to malfunction.  Do not run this
without instructions from Red Hat Support.
.SH "DESCRIPTION"
.PP 
The
.B clunfsops
command is an internal command used to manipulate clustered NFS services.

.SH "SEE ALSO"
nfs(5), rpc.nfsd(8)
