###############################################################################
###############################################################################
##
##  Copyright (C) Sistina Software, Inc.  1997-2003  All rights reserved.
##  Copyright (C) 2004 Red Hat, Inc.  All rights reserved.
##
##  This copyrighted material is made available to anyone wishing to use,
##  modify, copy, or redistribute it subject to the terms and conditions
##  of the GNU General Public License v.2.
##
###############################################################################
###############################################################################

TARGET= clubufflush.8 \
	clufindhostname.8 \
	clulog.8 \
	clurgmgrd.8 \
	clurmtabd.8 \
	clustat.8 \
	clusvcadm.8

include ../../make/defines.mk
include $(OBJDIR)/make/man.mk

check:
