###############################################################################
###############################################################################
##
##  Copyright (C) Sistina Software, Inc.  1997-2003  All rights reserved.
##  Copyright (C) 2004 Red Hat, Inc.  All rights reserved.
##
##  This copyrighted material is made available to anyone wishing to use,
##  modify, copy, or redistribute it subject to the terms and conditions
##  of the GNU General Public License v.2.
##
###############################################################################
###############################################################################

all: lock_gulmd gulm_tool

.PHONY: lock_gulmd clean dep depends

lock_gulmd:
	cd .. && ${MAKE} lock_gulmd

gulm_tool:
	cd .. && ${MAKE} gulm_tool

clean:
	cd .. && ${MAKE} clean

dep depends:
	cd .. && ${MAKE} depends

