###############################################################################
###############################################################################
##
##  Copyright (C) Sistina Software, Inc.  1997-2003  All rights reserved.
##  Copyright (C) 2004 Red Hat, Inc.  All rights reserved.
##
##  This copyrighted material is made available to anyone wishing to use,
##  modify, copy, or redistribute it subject to the terms and conditions
##  of the GNU General Public License v.2.
##
###############################################################################
###############################################################################

all:
	cd gfs2 && ${MAKE} all

install:
	cd gfs2 && ${MAKE} install

uninstall:
	cd gfs2 && ${MAKE} uninstall

clean:
	rm -rf *.patch linux-patched
	cd gfs2 && ${MAKE} clean

patches:
	cd gfs2 && ${MAKE} patches

