# This file was generated by configure from defines.mk.input
###############################################################################
###############################################################################
##
##  Copyright (C) Sistina Software, Inc.  1997-2003  All rights reserved.
##  Copyright (C) 2004 Red Hat, Inc.  All rights reserved.
##  
##  This copyrighted material is made available to anyone wishing to use,
##  modify, copy, or redistribute it subject to the terms and conditions
##  of the GNU General Public License v.2.
##
###############################################################################
###############################################################################

#Install Locations
sbindir ?= ${DESTDIR}//sbin
mandir ?= ${DESTDIR}//usr/share/man
libdir ?= ${DESTDIR}//usr/lib
incdir ?= ${DESTDIR}//usr/include
sharedir ?= ${DESTDIR}//usr/share/cluster

# Where's the kernel?
KERNEL_SRC = /tmp/cluster_build/cluster/rgmanager/../linux-2.6.9

# C Compiler defaults
CC = gcc

STRIP = strip
AR = ar
LD = ld
#RANLIB = echo
RANLIB = ranlib

# Default CFLAGS
CFLAGS += -Wall ${INCLUDE}
RELEASE_MAJOR = DEVEL
RELEASE_MINOR = 1098902155
RELEASE = DEVEL.1098902155
