.TH gfs2_quota 8

.SH NAME
gfs2_quota - Manipulate GFS2 disk quotas

.SH SYNOPSIS
.B gfs2_quota
<list|sync|get|limit|warn|check|init|reset> [\fIOPTION\fR]...

.SH DESCRIPTION
gfs2_quota is used to examine and change quota values in a GFS2 filesystem.
This command has a number of different actions.

GFS2(5.1) introduced a new linked list format for the quotas in the quota file.
This list format allows for faster \fBlist\fP, \fBcheck\fP and \fBinit\fP 
operations. Older GFS2 quota files may be migrated to this newer format using 
the \fBgfs2_quota reset\fP command.

.SH ACTIONS
.TP
\fBlist\fP
List the contents of the quota file.  Only IDs that have a non-zero hard limit,
warn limit, or value are printed.
.TP
\fBsync\fP
Sync any local quota changes to the quota file.
.TP
\fBget\fP
Get the current data for the ID specified by the -u or -g argument.
.TP
\fBlimit\fP
Set the current hard limit for the ID specified by the -u or -g argument to 
the value specified by the -l argument on the specified filesystem.
The filesystem won't let the user or group use more than this much space.
A value of zero here means that no limit is enforced.
.TP
\fBwarn\fP
Set the current warn limit for the ID specified by the -u or -g argument to 
the value specified by the -l argument on the specified filesystem.
The filesystem will start complaining to the user or group when more
than this much space is used.  A value of zero here means that the
user won't ever be warned.
.TP
\fBcheck\fP
Scan a filesystem and make sure that what's out there on the disk matches
what's in the quota file.  This is only accurate if the filesystem is
idle when this is running.  If there is a mismatch, it is printed to
stdout.  Note: GFS2 quotas are transactional and a quota check is \fBnot\fP
needed every time there is a system crash.
.TP
\fBinit\fP
Scan a filesystem and initialize the quota file with the values obtained
from the scan.  The filesystem should be idle when this is run.  You should
only need to do this if you upgrade a pre-quota GFS2 filesystem (pre-GFS2 5.1).
.TP
\fBreset\fP
The \fBreset\fP operation will truncate the quota file and all quota 
information (values, limits, warnings) will be lost.  All quota limits and 
warnings will have to be reassigned after this operation.

.SH OPTIONS
\fB-b\fP
The units for disk space are filesystem blocks.
.TP
\fB-f\fP \fIDirectory\fR 
Specifies which filesystem to perform the action on.
.TP
\fB-g\fP \fIGID\fR 
Specifies the group ID for get, limit, or warn.  It can be either
the group name from the group file, or the GID number.
.TP
\fB-h\fP
Print  out  a  help  message  describing  available
options, then exit.
.TP
\fB-k\fP
The units for disk space are kilobytes.
.TP
\fB-l\fP \fISize\fR 
Specifies the new value for the limit or warn actions.
The value is assumed to be in the units specified by the
-m, -k, -s, -b arguments.  The default is megabytes.
.TP
\fB-m\fP
The units for disk space are megabytes.  This is the default.
.TP
\fB-n\fP
Don't try to resolve UIDs and GIDs into user and group names.
.TP
\fB-s\fP
The units for disk space are sectors (512-byte blocks).
.TP
\fB-u\fP \fIUID\fR 
Specifies the user ID for get, limit, or warn.  It can be either
the username from the password file, or the UID number.
.TP
\fB-V\fP
Print program version information, then exit.

.SH EXAMPLE
To set the hard limit for user "nobody" to
1048576 kilobytes on filesystem /gfs20

gfs2_quota limit -l 1048576 -k -u nobody -f /gfs20

