.TH gfs2_convert 8

.SH NAME
gfs2_convert - Convert a GFS1 filesystem to GFS2

.SH SYNOPSIS
.B gfs2_convert
[\fIOPTION\fR]... \fIDEVICE\fR

.SH DESCRIPTION
gfs2_convert is used to convert a filesystem from GFS1 to GFS2.

.SH OPTIONS
.TP
\fB-h\fP
Help.

This prints out the proper command line usage syntax.
.TP
\fB-q\fP
Quiet.  Print less information while running.
.TP
\fB-n\fP
No to all questions.
.TP
\fB-V\fP
Print program Version information only.

Print out the current version name.
.TP
\fB-v\fP
Verbose operation.

Print more information while running.
.TP
\fB-y\fP
Yes to all questions.

By specifying this option, gfs2_convert will not prompt before making
changes.

.SH EXAMPLE
.TP
gfs2_convert /dev/vg0/lvol0
This will convert the Global File System on the block device
"/dev/vg0/lvol0" to gfs2 format.
