.TH gfs2_grow 8

.SH NAME
gfs2_grow - Expand a GFS2 filesystem

.SH SYNOPSIS
.B gfs2_grow
[\fIOPTION\fR]... <\fIDEVICE\fR|\fIMOINTPOINT\fR>...

.SH DESCRIPTION
gfs2_grow is used to expand a GFS2 filesystem after the device
upon which the filesystem resides has also been expanded.  By
running gfs2_grow on a GFS2 filesystem, you are requesting that
any spare space between the current end of the filesystem and
the end of the device is filled with a newly initialized GFS2
filesystem extension.  When this operation is complete, the resource
index for the filesystem is updated so that all nodes in the
cluster can use the extra storage space which has been added.

You may only run gfs2_grow on a mounted filesystem; expansion of 
unmounted filesystems is not supported.  You only need to
run gfs2_grow on one node in the cluster.  All the other nodes will
see the expansion has occurred and automatically start to use the
newly available space.

You must be superuser to execute \fBgfs2_grow\fP.  The gfs2_grow
tool tries to prevent you from corrupting your filesystem by checking as
many of the likely problems as it can.  When expanding a filesystem,
only the last step of updating the resource index affects the currently
mounted filesystem and so failure part way through the expansion process
should leave your filesystem in its original unexpanded state.

You can run gfs2_grow with the \fB-T\fP flag to get a display
of the current state of a mounted GFS2 filesystem.

.SH OPTIONS
.TP
\fB-D\fP
Print out debugging information about the filesystem layout.
.TP
\fB-h\fP
Prints out a short usage message and exits.
.TP
\fB-q\fP
Be quiet.  Don't print anything.
.TP
\fB-r MegaBytes\fP
gfs2_grow will try to make the new Resource Groups about this big.
The default is 256 MB.
.TP
\fB-T\fP
Test. Do all calculations, but do not write any data to the disk and do
not expand the filesystem. This is used to discover what the tool would
have done were it run without this flag.
.TP
\fB-V\fP
Version. Print out version information, then exit.

.SH SEE ALSO
gfs2_mkfs(8) gfs2_jadd(8)
