###############################################################################
###############################################################################
##
##  Copyright (C) 2004 Red Hat, Inc.  All rights reserved.
##
##  This copyrighted material is made available to anyone wishing to use,
##  modify, copy, or redistribute it subject to the terms and conditions
##  of the GNU General Public License v.2.
##
###############################################################################
###############################################################################
 
all:
	cd lib && ${MAKE} all
 
clean:
	cd lib && ${MAKE} clean

distclean: clean
	rm -f make/defines.mk
 
install:
	cd lib && ${MAKE} install

uninstall:
	cd lib && ${MAKE} uninstall
