.TH "mkqdisk" "8" "July 2006" "" "Quorum Disk Management"
.SH "NAME"
mkqdisk \- Cluster Quorum Disk Utility
.SH "WARNING"
Use of this command can cause the cluster to malfunction.
.SH "SYNOPSIS"
\fBmkqdisk [\-?|\-h] | [\-L] | [\-f \fPlabel\fB] [\-c \fPdevice \fB -l \fPlabel\fB] [-d [-d ...]]
.SH "DESCRIPTION"
.PP 
The \fBmkqdisk\fP command is used to create a new quorum disk or display
existing quorum disks accessible from a given cluster node.
.SH "OPTIONS"
.IP "\-c device \-l label"
Initialize a new cluster quorum disk.  This will destroy all data on the given
device.  If a cluster is currently using that device as a quorum disk, the
entire cluster will malfunction.  Do not run this on an active cluster when
qdiskd is running.  Only one device on the SAN should ever have the given
label; using multiple different devices is currently not supported (it is
expected a RAID array is used for quorum disk redundancy).  The label can be
any textual string up to 127 characters - and is therefore enough space to hold
a UUID created with uuidgen(1).
.IP "\-f label"
Find the cluster quorum disk with the given label and display information about it.
.IP "\-L"
Display information on all accessible cluster quorum disks.
.IP "\-d"
Increase debugging level.  Specify multiple times for more information.
Currently, specifying more than twice has no effect.

.SH "SEE ALSO"
qdisk(5), qdiskd(8), uuidgen(1)
