.TH "qdiskd" "8" "July 2006" "" "Quorum Disk Management"
.SH "NAME"
qdiskd \- Cluster Quorum Disk Daemon
.SH "SYNOPSIS"
\fBqdiskd [\-f] [\-d]
.SH "DESCRIPTION"
.PP 
The \fBqdiskd\fP daemon talks to CMAN and provides a mechanism for determining
node-fitness in a cluster environment.  See
.B
qdisk(5)
for configuration information.
.SH "OPTIONS"
.IP "\-f"
Run in the foreground (do not fork / daemonize).
.IP "\-d"
Enable debug output.
.IP "\-Q"
Close stdin/out/err immediately before doing validations.  This
is primarily for use when being called from an init script.  Using
this option will stop all output, and can not be used with the -d 
option.

.SH "SEE ALSO"
mkqdisk(8), qdisk(5), cman(5)
