.TH gnbd 8

.SH NAME
gnbd \- GNBD reference guide

.SH SYNOPSIS
Overview of manpages and their locations

.SH DESCRIPTION
The GFS Network Block Device has two parts, the client (which includes the
\fBgnbd.ko\fP module and  \fBgnbd_import\fP, \fBgnbd_recvd\fP, and
\fBgnbd_monitor\fP programs) and the server
(which include the \fBgnbd_serv\fP, \fBgnbd_clusterd\fP, and \fBgnbd_export\fP
programs).  The GNBD server allows a computer
to export multiple block devices or files (GNBDs).  The GNBD client allows a
computer to import these GNBDs, and use them as if they were local block
devices.  The primary difference between GNBD and NBD (the network block
device distributed with the Linux kernel) is GNBD's ability to have multiple
clients all accessing the same served file or block device at the same
time.   

The GNBD documentation has been split into a number of sections.  Please
refer to the table below to determine which man page coincides with the
command/feature you are looking for.

.TP 16
gnbd
GNBD overview (this man page)
.TP
gnbd_import
Configure a GNBD Client
.TP
gnbd_export
Configure a GNBD Server
.TP
fence_gnbd
Fence method for GNBD

.SH SEE ALSO
gfs(8), fence(8), fence_gnbd(8)
