.TH ccs 7

.SH NAME
ccs - Cluster Configuration System

.SH DESCRIPTION

CCS is the system that manages the /etc/cluster/cluster.conf file on
cluster nodes.  The primary users of cluster.conf are the cman cluster
manager, the fenced fencing daemon and rgmanager which manages H/A
services.

libccs is the API used by the programs and daemons above to read
cluster.conf information.  libccs requests go through the ccsd daemon.
ccsd needs to be started before the cman cluster manager is started.

The ccs_test program can be used to test the ccs system and read
cluster.conf values.

.SH SEE ALSO
ccsd(8), ccs_tool(8), ccs_test(8), cluster.conf(5), cman(5)

