/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.7 2003/04/08 14:57:04 dts12 Exp $
 */

#include "clusterMIB.h"

//#include "ClusterMonitor.h"
#include "clusterMonitorSnmp.h"


using namespace ClusterMonitoring;
using namespace std;


static unsigned int getStatusCode();
static string getStatusDescription(unsigned int code);


void
initialize_clusterMIB(void)
{
    static oid      rhcClusterFailedServicesNum_oid[] =
        { 1, 3, 6, 1, 4, 1, 8072, 2, 5, 1, 12 };
    static oid      rhcClusterStatusString_oid[] =
        { 1, 3, 6, 1, 4, 1, 8072, 2, 5, 1, 3 };
    static oid      rhcClusterVotes_oid[] =
        { 1, 3, 6, 1, 4, 1, 8072, 2, 5, 1, 4 };
    static oid      rhcClusterStoppedServicesNum_oid[] =
        { 1, 3, 6, 1, 4, 1, 8072, 2, 5, 1, 11 };
    static oid      rhcClusterAvailNodesNum_oid[] =
        { 1, 3, 6, 1, 4, 1, 8072, 2, 5, 1, 7 };
    static oid      rhcClusterServicesNum_oid[] =
        { 1, 3, 6, 1, 4, 1, 8072, 2, 5, 1, 9 };
    static oid      rhcClusterName_oid[] =
        { 1, 3, 6, 1, 4, 1, 8072, 2, 5, 1, 1 };
    static oid      rhcClusterStatusCode_oid[] =
        { 1, 3, 6, 1, 4, 1, 8072, 2, 5, 1, 2 };
    static oid      rhcClusterUnavailNodesNum_oid[] =
        { 1, 3, 6, 1, 4, 1, 8072, 2, 5, 1, 8 };
    static oid      rhcClusterNodesNum_oid[] =
        { 1, 3, 6, 1, 4, 1, 8072, 2, 5, 1, 6 };
    static oid      rhcClusterRunningServicesNum_oid[] =
        { 1, 3, 6, 1, 4, 1, 8072, 2, 5, 1, 10 };
    static oid      rhcClusterVotesNeededForQuorum_oid[] =
        { 1, 3, 6, 1, 4, 1, 8072, 2, 5, 1, 5 };
    
    DEBUGMSGTL(("libClusterMonitorSnmp", "Initializing\n"));
    
    netsnmp_register_scalar(netsnmp_create_handler_registration
                            ("rhcClusterFailedServicesNum",
                             handle_rhcClusterFailedServicesNum,
                             rhcClusterFailedServicesNum_oid,
                             OID_LENGTH(rhcClusterFailedServicesNum_oid),
                             HANDLER_CAN_RONLY));
    netsnmp_register_scalar(netsnmp_create_handler_registration
                            ("rhcClusterStatusString",
                             handle_rhcClusterStatusString,
                             rhcClusterStatusString_oid,
                             OID_LENGTH(rhcClusterStatusString_oid),
                             HANDLER_CAN_RONLY));
    netsnmp_register_scalar(netsnmp_create_handler_registration
                            ("rhcClusterVotes", handle_rhcClusterVotes,
                             rhcClusterVotes_oid,
                             OID_LENGTH(rhcClusterVotes_oid),
                             HANDLER_CAN_RONLY));
    netsnmp_register_scalar(netsnmp_create_handler_registration
                            ("rhcClusterStoppedServicesNum",
                             handle_rhcClusterStoppedServicesNum,
                             rhcClusterStoppedServicesNum_oid,
                             OID_LENGTH(rhcClusterStoppedServicesNum_oid),
                             HANDLER_CAN_RONLY));
    netsnmp_register_scalar(netsnmp_create_handler_registration
                            ("rhcClusterAvailNodesNum",
                             handle_rhcClusterAvailNodesNum,
                             rhcClusterAvailNodesNum_oid,
                             OID_LENGTH(rhcClusterAvailNodesNum_oid),
                             HANDLER_CAN_RONLY));
    netsnmp_register_scalar(netsnmp_create_handler_registration
                            ("rhcClusterServicesNum",
                             handle_rhcClusterServicesNum,
                             rhcClusterServicesNum_oid,
                             OID_LENGTH(rhcClusterServicesNum_oid),
                             HANDLER_CAN_RONLY));
    netsnmp_register_scalar(netsnmp_create_handler_registration
                            ("rhcClusterName", handle_rhcClusterName,
                             rhcClusterName_oid,
                             OID_LENGTH(rhcClusterName_oid),
                             HANDLER_CAN_RONLY));
    netsnmp_register_scalar(netsnmp_create_handler_registration
                            ("rhcClusterStatusCode",
                             handle_rhcClusterStatusCode,
                             rhcClusterStatusCode_oid,
                             OID_LENGTH(rhcClusterStatusCode_oid),
                             HANDLER_CAN_RONLY));
    netsnmp_register_scalar(netsnmp_create_handler_registration
                            ("rhcClusterUnavailNodesNum",
                             handle_rhcClusterUnavailNodesNum,
                             rhcClusterUnavailNodesNum_oid,
                             OID_LENGTH(rhcClusterUnavailNodesNum_oid),
                             HANDLER_CAN_RONLY));
    netsnmp_register_scalar(netsnmp_create_handler_registration
                            ("rhcClusterNodesNum",
                             handle_rhcClusterNodesNum,
                             rhcClusterNodesNum_oid,
                             OID_LENGTH(rhcClusterNodesNum_oid),
                             HANDLER_CAN_RONLY));
    netsnmp_register_scalar(netsnmp_create_handler_registration
                            ("rhcClusterRunningServicesNum",
                             handle_rhcClusterRunningServicesNum,
                             rhcClusterRunningServicesNum_oid,
                             OID_LENGTH(rhcClusterRunningServicesNum_oid),
                             HANDLER_CAN_RONLY));
    netsnmp_register_scalar(netsnmp_create_handler_registration
                            ("rhcClusterVotesNeededForQuorum",
                             handle_rhcClusterVotesNeededForQuorum,
                             rhcClusterVotesNeededForQuorum_oid,
                             OID_LENGTH
                             (rhcClusterVotesNeededForQuorum_oid),
                             HANDLER_CAN_RONLY));
}


unsigned int 
getStatusCode(Cluster* cluster)
{
  unsigned int code = 1; // OK
  
  if (cluster->getFailedServices().size() != 0)
    // service failed
    code = (code & ~1) | 2;
  
  if (cluster->getStoppedServices().size() != 0)
    // service not running
    code = (code & ~1) | 4;
  
  if (cluster->getUnclusteredNodes().size() != 0)
    // unavailable node
    code = (code & ~1) | 8;
  
  if (cluster->getVotes() < cluster->getMinQuorum())
    // not quorumed
    code = (code & ~1) | 16;
  
  if (cluster->getUnclusteredNodes().size() == cluster->getNodes().size())
    // cluster stopped
    code = (code & ~1) | 32;
  
  return code;
}

string
getStatusDescription(unsigned int code)
{
  if (code == 1)
    return "All services and nodes functional";
  if (code & 32)
    return "Cluster stopped (all services stopped)";
  if (code & 16)
    return "Not quorumed (all services stopped)";
  
  string descr;
  if (code & 2) {
    string c = "Some services failed";
    if (descr.size() == 0)
      descr = c;
    else
      descr += ", " + c;
  }
  if (code & 4) {
    string c = "Some services not running";
    if (descr.size() == 0)
      descr = c;
    else
      descr += ", " + c;
  }
  if (code & 8) {
    string c = "Some nodes unavailable";
    if (descr.size() == 0)
      descr = c;
    else
      descr += ", " + c;
  }
  return descr;
}


int
handle_rhcClusterFailedServicesNum(netsnmp_mib_handler *handler,
                                   netsnmp_handler_registration *reginfo,
                                   netsnmp_agent_request_info *reqinfo,
                                   netsnmp_request_info *requests)
{
  try {
    counting_auto_ptr<Cluster> cluster = monitor.getCluster();
    if(cluster.get() == NULL)
      return SNMP_ERR_NOERROR;
    
    unsigned int num = cluster->getFailedServices().size();
    
    /*
     * We are never called for a GETNEXT if it's registered as a
     * "instance", as it's "magically" handled for us.  
     */
    
    /*
     * a instance handler also only hands us one request at a time, so
     * we don't need to loop over a list of requests; we'll only get one. 
     */
    
    switch (reqinfo->mode) {
      
    case MODE_GET:
      snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
			       (u_char *)
			       &num,
			       sizeof(num));
      break;
      
    default:
      /*
       * we should never get here, so this is a really bad error 
       */
      return SNMP_ERR_GENERR;
    }
  }
  catch( ... ) {
    return SNMP_ERR_GENERR;
  }
  return SNMP_ERR_NOERROR;
}

int
handle_rhcClusterStatusString(netsnmp_mib_handler *handler,
                              netsnmp_handler_registration *reginfo,
                              netsnmp_agent_request_info *reqinfo,
                              netsnmp_request_info *requests)
{
  try {
    counting_auto_ptr<Cluster> cluster = monitor.getCluster();
    if(cluster.get() == NULL)
      return SNMP_ERR_NOERROR;
    
    unsigned int code = getStatusCode(cluster.get());
    string str = getStatusDescription(code);
    
    /*
     * We are never called for a GETNEXT if it's registered as a
     * "instance", as it's "magically" handled for us.  
     */
    
    /*
     * a instance handler also only hands us one request at a time, so
     * we don't need to loop over a list of requests; we'll only get one. 
     */
    
    switch (reqinfo->mode) {
      
    case MODE_GET:
      snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
			       (u_char *)
			       str.c_str(),
			       str.size());
      break;
      
    default:
      /*
       * we should never get here, so this is a really bad error 
       */
      return SNMP_ERR_GENERR;
    }
  }
  catch( ... ) {
    return SNMP_ERR_GENERR;
  }
  return SNMP_ERR_NOERROR;
}

int
handle_rhcClusterVotes(netsnmp_mib_handler *handler,
                       netsnmp_handler_registration *reginfo,
                       netsnmp_agent_request_info *reqinfo,
                       netsnmp_request_info *requests)
{
  try {
    counting_auto_ptr<Cluster> cluster = monitor.getCluster();
    if(cluster.get() == NULL)
      return SNMP_ERR_NOERROR;
    
    unsigned int num = cluster->getVotes();
  
    /*
     * We are never called for a GETNEXT if it's registered as a
     * "instance", as it's "magically" handled for us.  
     */

    /*
     * a instance handler also only hands us one request at a time, so
     * we don't need to loop over a list of requests; we'll only get one. 
     */

    switch (reqinfo->mode) {

    case MODE_GET:
        snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                 (u_char *)
                                 &num,
                                 sizeof(num));
        break;
	
    default:
      /*
       * we should never get here, so this is a really bad error 
       */
      return SNMP_ERR_GENERR;
    }
  }
  catch( ... ) {
    return SNMP_ERR_GENERR;
  }
  return SNMP_ERR_NOERROR;
}

int
handle_rhcClusterStoppedServicesNum(netsnmp_mib_handler *handler,
                                    netsnmp_handler_registration *reginfo,
                                    netsnmp_agent_request_info *reqinfo,
                                    netsnmp_request_info *requests)
{
  try {
    counting_auto_ptr<Cluster> cluster = monitor.getCluster();
    if(cluster.get() == NULL)
      return SNMP_ERR_NOERROR;
    
    unsigned int num = cluster->getStoppedServices().size();
  
    /*
     * We are never called for a GETNEXT if it's registered as a
     * "instance", as it's "magically" handled for us.  
     */

    /*
     * a instance handler also only hands us one request at a time, so
     * we don't need to loop over a list of requests; we'll only get one. 
     */

    switch (reqinfo->mode) {

    case MODE_GET:
        snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                 (u_char *)
                                 &num,
                                 sizeof(num));
        break;
	
    default:
      /*
       * we should never get here, so this is a really bad error 
       */
      return SNMP_ERR_GENERR;
    }
  }
  catch( ... ) {
    return SNMP_ERR_GENERR;
  }
  return SNMP_ERR_NOERROR;
}

int
handle_rhcClusterAvailNodesNum(netsnmp_mib_handler *handler,
                               netsnmp_handler_registration *reginfo,
                               netsnmp_agent_request_info *reqinfo,
                               netsnmp_request_info *requests)
{
  try {
    counting_auto_ptr<Cluster> cluster = monitor.getCluster();
    if(cluster.get() == NULL)
      return SNMP_ERR_NOERROR;
    
    unsigned int num = cluster->getClusteredNodes().size();
  
    /*
     * We are never called for a GETNEXT if it's registered as a
     * "instance", as it's "magically" handled for us.  
     */
    
    /*
     * a instance handler also only hands us one request at a time, so
     * we don't need to loop over a list of requests; we'll only get one. 
     */
    
    switch (reqinfo->mode) {

    case MODE_GET:
        snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                 (u_char *)
                                 &num,
                                 sizeof(num));
        break;
	
    default:
      /*
       * we should never get here, so this is a really bad error 
       */
      return SNMP_ERR_GENERR;
    }
  }
  catch( ... ) {
    return SNMP_ERR_GENERR;
  }
  return SNMP_ERR_NOERROR;
}

int
handle_rhcClusterServicesNum(netsnmp_mib_handler *handler,
                             netsnmp_handler_registration *reginfo,
                             netsnmp_agent_request_info *reqinfo,
                             netsnmp_request_info *requests)
{
  try {
    counting_auto_ptr<Cluster> cluster = monitor.getCluster();
    if(cluster.get() == NULL)
      return SNMP_ERR_NOERROR;
    
    unsigned int num = cluster->getServices().size();
  
    /*
     * We are never called for a GETNEXT if it's registered as a
     * "instance", as it's "magically" handled for us.  
     */

    /*
     * a instance handler also only hands us one request at a time, so
     * we don't need to loop over a list of requests; we'll only get one. 
     */

    switch (reqinfo->mode) {

    case MODE_GET:
        snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                 (u_char *)
                                 &num,
                                 sizeof(num));
        break;

    default:
      /*
       * we should never get here, so this is a really bad error 
       */
      return SNMP_ERR_GENERR;
    }
  }
  catch( ... ) {
    return SNMP_ERR_GENERR;
  }
  return SNMP_ERR_NOERROR;
}

int
handle_rhcClusterName(netsnmp_mib_handler *handler,
                      netsnmp_handler_registration *reginfo,
                      netsnmp_agent_request_info *reqinfo,
                      netsnmp_request_info *requests)
{
  try {
    counting_auto_ptr<Cluster> cluster = monitor.getCluster();
    if(cluster.get() == NULL)
      return SNMP_ERR_NOERROR;
    
    string name = cluster->name;
  
    /*
     * We are never called for a GETNEXT if it's registered as a
     * "instance", as it's "magically" handled for us.  
     */

    /*
     * a instance handler also only hands us one request at a time, so
     * we don't need to loop over a list of requests; we'll only get one. 
     */

    switch (reqinfo->mode) {

    case MODE_GET:
        snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                 (u_char *)
                                 name.c_str(),
                                 name.size());
        break;

    default:
      /*
       * we should never get here, so this is a really bad error 
       */
      return SNMP_ERR_GENERR;
    }
  }
  catch( ... ) {
    return SNMP_ERR_GENERR;
  }
  return SNMP_ERR_NOERROR;
}

int
handle_rhcClusterStatusCode(netsnmp_mib_handler *handler,
                            netsnmp_handler_registration *reginfo,
                            netsnmp_agent_request_info *reqinfo,
                            netsnmp_request_info *requests)
{
  try {
    counting_auto_ptr<Cluster> cluster = monitor.getCluster();
    if(cluster.get() == NULL)
      return SNMP_ERR_NOERROR;
    
    unsigned int code = getStatusCode(cluster.get());
    
    /*
     * We are never called for a GETNEXT if it's registered as a
     * "instance", as it's "magically" handled for us.  
     */

    /*
     * a instance handler also only hands us one request at a time, so
     * we don't need to loop over a list of requests; we'll only get one. 
     */

    switch (reqinfo->mode) {

    case MODE_GET:
        snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                 (u_char *)
                                 &code,
                                 sizeof(code));
        break;

    default:
      /*
       * we should never get here, so this is a really bad error 
       */
      return SNMP_ERR_GENERR;
    }
  }
  catch( ... ) {
    return SNMP_ERR_GENERR;
  }
  return SNMP_ERR_NOERROR;
}

int
handle_rhcClusterUnavailNodesNum(netsnmp_mib_handler *handler,
                                 netsnmp_handler_registration *reginfo,
                                 netsnmp_agent_request_info *reqinfo,
                                 netsnmp_request_info *requests)
{
  try {
    counting_auto_ptr<Cluster> cluster = monitor.getCluster();
    if(cluster.get() == NULL)
      return SNMP_ERR_NOERROR;
    
    unsigned int num = cluster->getUnclusteredNodes().size();
      
    /*
     * We are never called for a GETNEXT if it's registered as a
     * "instance", as it's "magically" handled for us.  
     */

    /*
     * a instance handler also only hands us one request at a time, so
     * we don't need to loop over a list of requests; we'll only get one. 
     */

    switch (reqinfo->mode) {

    case MODE_GET:
        snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                 (u_char *)
                                 &num,
                                 sizeof(num));
        break;

    default:
      /*
       * we should never get here, so this is a really bad error 
       */
      return SNMP_ERR_GENERR;
    }
  }
  catch( ... ) {
    return SNMP_ERR_GENERR;
  }
  return SNMP_ERR_NOERROR;
}

int
handle_rhcClusterNodesNum(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info *reqinfo,
                          netsnmp_request_info *requests)
{
  try {
    counting_auto_ptr<Cluster> cluster = monitor.getCluster();
    if(cluster.get() == NULL)
      return SNMP_ERR_NOERROR;
    
    unsigned int num = cluster->getNodes().size();
  
    /*
     * We are never called for a GETNEXT if it's registered as a
     * "instance", as it's "magically" handled for us.  
     */

    /*
     * a instance handler also only hands us one request at a time, so
     * we don't need to loop over a list of requests; we'll only get one. 
     */

    switch (reqinfo->mode) {

    case MODE_GET:
        snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                 (u_char *)
                                 &num,
                                 sizeof(num));
        break;

    default:
      /*
       * we should never get here, so this is a really bad error 
       */
      return SNMP_ERR_GENERR;
    }
  }
  catch( ... ) {
    return SNMP_ERR_GENERR;
  }
  return SNMP_ERR_NOERROR;
}

int
handle_rhcClusterRunningServicesNum(netsnmp_mib_handler *handler,
                                    netsnmp_handler_registration *reginfo,
                                    netsnmp_agent_request_info *reqinfo,
                                    netsnmp_request_info *requests)
{
  try {
    counting_auto_ptr<Cluster> cluster = monitor.getCluster();
    if(cluster.get() == NULL)
      return SNMP_ERR_NOERROR;
    
    unsigned int num = cluster->getRunningServices().size();
    
    /*
     * We are never called for a GETNEXT if it's registered as a
     * "instance", as it's "magically" handled for us.  
     */

    /*
     * a instance handler also only hands us one request at a time, so
     * we don't need to loop over a list of requests; we'll only get one. 
     */

    switch (reqinfo->mode) {

    case MODE_GET:
        snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                 (u_char *)
                                 &num,
                                 sizeof(num));
        break;

    default:
      /*
       * we should never get here, so this is a really bad error 
       */
      return SNMP_ERR_GENERR;
    }
  }
  catch( ... ) {
    return SNMP_ERR_GENERR;
  }
  return SNMP_ERR_NOERROR;
}

int
handle_rhcClusterVotesNeededForQuorum(netsnmp_mib_handler *handler,
                                      netsnmp_handler_registration
                                      *reginfo,
                                      netsnmp_agent_request_info *reqinfo,
                                      netsnmp_request_info *requests)
{
  try {
    counting_auto_ptr<Cluster> cluster = monitor.getCluster();
    if(cluster.get() == NULL)
      return SNMP_ERR_NOERROR;
    
    unsigned int num = cluster->getMinQuorum();
    
    /*
     * We are never called for a GETNEXT if it's registered as a
     * "instance", as it's "magically" handled for us.  
     */

    /*
     * a instance handler also only hands us one request at a time, so
     * we don't need to loop over a list of requests; we'll only get one. 
     */

    switch (reqinfo->mode) {

    case MODE_GET:
        snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                 (u_char *)
                                 &num,
                                 sizeof(num));
        break;

    default:
      /*
       * we should never get here, so this is a really bad error 
       */
      return SNMP_ERR_GENERR;
    }
  }
  catch( ... ) {
    return SNMP_ERR_GENERR;
  }
  return SNMP_ERR_NOERROR;
}
