/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.7 2003/04/08 14:57:04 dts12 Exp $
 */

#ifndef clusterMIB_h
#define clusterMIB_h

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>


void initialize_clusterMIB(void);

extern "C"
{

Netsnmp_Node_Handler handle_rhcClusterFailedServicesNum;
Netsnmp_Node_Handler handle_rhcClusterStatusString;
Netsnmp_Node_Handler handle_rhcClusterVotes;
Netsnmp_Node_Handler handle_rhcClusterStoppedServicesNum;
Netsnmp_Node_Handler handle_rhcClusterAvailNodesNum;
Netsnmp_Node_Handler handle_rhcClusterServicesNum;
Netsnmp_Node_Handler handle_rhcClusterName;
Netsnmp_Node_Handler handle_rhcClusterStatusCode;
Netsnmp_Node_Handler handle_rhcClusterUnavailNodesNum;
Netsnmp_Node_Handler handle_rhcClusterNodesNum;
Netsnmp_Node_Handler handle_rhcClusterRunningServicesNum;
Netsnmp_Node_Handler handle_rhcClusterVotesNeededForQuorum;

};


#endif  /* clusterMIB_h */
