/*
  Copyright Red Hat, Inc. 2005

  This program is free software; you can redistribute it and/or modify it
  under the terms of the GNU General Public License as published by the
  Free Software Foundation; either version 2, or (at your option) any
  later version.

  This program is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; see the file COPYING.  If not, write to the
  Free Software Foundation, Inc.,  675 Mass Ave, Cambridge, 
  MA 02139, USA.
*/
/*
 * Author: Stanko Kupcevic <kupcevic@redhat.com>
 */
/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.7 2003/04/08 14:57:04 dts12 Exp $
 */


#ifndef clusterMIB_h
#define clusterMIB_h

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>


void initialize_clusterMIB(void);

extern "C"
{

Netsnmp_Node_Handler handle_rhcMIBVersion;
Netsnmp_Node_Handler handle_rhcClusterName;
Netsnmp_Node_Handler handle_rhcClusterStatusCode;
Netsnmp_Node_Handler handle_rhcClusterStatusDesc;
Netsnmp_Node_Handler handle_rhcClusterVotes;
Netsnmp_Node_Handler handle_rhcClusterQuorate;
Netsnmp_Node_Handler handle_rhcClusterFailedServicesNum;
Netsnmp_Node_Handler handle_rhcClusterFailedServicesNames;
Netsnmp_Node_Handler handle_rhcClusterStoppedServicesNum;
Netsnmp_Node_Handler handle_rhcClusterStoppedServicesNames;
Netsnmp_Node_Handler handle_rhcClusterAvailNodesNum;
Netsnmp_Node_Handler handle_rhcClusterAvailNodesNames;
Netsnmp_Node_Handler handle_rhcClusterServicesNum;
Netsnmp_Node_Handler handle_rhcClusterServicesNames;
Netsnmp_Node_Handler handle_rhcClusterUnavailNodesNum;
Netsnmp_Node_Handler handle_rhcClusterUnavailNodesNames;
Netsnmp_Node_Handler handle_rhcClusterNodesNum;
Netsnmp_Node_Handler handle_rhcClusterNodesNames;
Netsnmp_Node_Handler handle_rhcClusterRunningServicesNum;
Netsnmp_Node_Handler handle_rhcClusterRunningServicesNames;
Netsnmp_Node_Handler handle_rhcClusterVotesNeededForQuorum;

};


#endif  /* clusterMIB_h */
