/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate.conf,v 5.6 2003/02/20 00:52:07 hardaker Exp $
 */

/***********************************************************************
 *   This file is auto-generated and SHOULD NOT BE EDITED by hand.
 *   Modify the rhcNodesTable_checkfns_local.[ch] files insead.
 *   (so that you can regenerate this one as mib2c improvements are made)
 ***********************************************************************/

#ifndef nodesMIB_checkfns_h
#define nodesMIB_checkfns_h

extern "C" {
/** make sure we load the functions that you can modify */
config_require(rhcNodesTable_checkfns_local)

    /*
     * these functions are designed to check incoming values for 
     * columns in the rhcNodesTable table for legality with respect to 
     * datatype and value.
     */
};


#endif  // nodesMIB_checkfns_h
