/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.column_defines.conf,v 5.1 2002/05/08 05:42:47 hardaker Exp $
 */

#ifndef nodesMIB_columns_h
#define nodesMIB_columns_h


/*
 * column number definitions for table rhcNodesTable 
 */
#define COLUMN_RHCNODENAME		1
#define COLUMN_RHCNODESTATUSCODE		2
#define COLUMN_RHCNODESTATUSSTRING		3
#define COLUMN_RHCNODERUNNINGSERVICESNUM		4


#endif  // nodesMIB_columns_h
