/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate_access.conf,v 1.6 2003/09/29 22:30:36 hardaker Exp $
 */

#ifndef nodesMIB_h
#define nodesMIB_h

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>


void initialize_nodesMIB(void);

extern "C" {
config_require(rhcNodesTable_access)
       /** other required module components */
       config_require(rhcNodesTable_checkfns)
       
       /*
	* function declarations 
	*/
       void            init_rhcNodesTable(void);
       void            initialize_table_rhcNodesTable(void);
       Netsnmp_Node_Handler rhcNodesTable_handler;
};

#include "nodesMIB_columns.h"

#include "nodesMIB_enums.h"


#endif // nodesMIB_h
