/*
 * Note: this file originally auto-generated by mib2c using
 *        : : mib2c.check_values_local.conf,v 5.1.2.1 2004/05/04 23:35:32 hardaker Exp $
 * 
 */

#ifndef servicesMIB_checkfns_local_h
#define servicesMIB_checkfns_local_h

/*
 * these functions are designed to check incoming values for 
 * columns in the rhcServicesTable table for legality with respect to 
 * datatype and value according to local conventions.  You should modify
 * them as appropriate.  They will be called from parent check_value
 * functions that are auto-generated using mib2c and the parent functions
 * should NOT be modified.
 */


#endif  // servicesMIB_checkfns_local_h
