/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.column_defines.conf,v 5.1 2002/05/08 05:42:47 hardaker Exp $
 */

#ifndef servicesMIB_columns_h
#define servicesMIB_columns_h

/*
 * column number definitions for table rhcServicesTable 
 */
#define COLUMN_RHCSERVICENAME		1
#define COLUMN_RHCSERVICESTATUSCODE		2
#define COLUMN_RHCSERVICESTATUSSTRING		3
#define COLUMN_RHCSERVICESTARTMODE		4
#define COLUMN_RHCSERVICERUNNINGONNODE		5

#endif  // servicesMIB_columns_h
