/*
  Copyright Red Hat, Inc. 2005

  This program is free software; you can redistribute it and/or modify it
  under the terms of the GNU General Public License as published by the
  Free Software Foundation; either version 2, or (at your option) any
  later version.

  This program is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; see the file COPYING.  If not, write to the
  Free Software Foundation, Inc.,  675 Mass Ave, Cambridge, 
  MA 02139, USA.
*/
/*
 * Author: Stanko Kupcevic <kupcevic@redhat.com>
 */
/*
 * Note: this file originally auto-generated by mib2c using
 *        : : mib2c.check_values_local.conf,v 5.1.2.1 2004/05/04 23:35:32 hardaker Exp $
 */


#ifndef servicesMIB_checkfns_local_h
#define servicesMIB_checkfns_local_h

/*
 * these functions are designed to check incoming values for 
 * columns in the rhcServicesTable table for legality with respect to 
 * datatype and value according to local conventions.  You should modify
 * them as appropriate.  They will be called from parent check_value
 * functions that are auto-generated using mib2c and the parent functions
 * should NOT be modified.
 */


#endif  // servicesMIB_checkfns_local_h
