/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate_access.conf,v 1.6 2003/09/29 22:30:36 hardaker Exp $
 */

#ifndef servicesMIB_h
#define servicesMIB_h

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>


void initialize_servicesMIB(void);

extern "C" {
config_require(rhcServicesTable_access)
    config_require(rhcServicesTable_checkfns)

    /*
     * function declarations 
     */
     void            init_rhcServicesTable(void);
     void            initialize_table_rhcServicesTable(void);
     Netsnmp_Node_Handler rhcServicesTable_handler;
};


#include "servicesMIB_columns.h"
#include "servicesMIB_enums.h"

#endif // servicesMIB_h
