/*
  Copyright Red Hat, Inc. 2005

  This program is free software; you can redistribute it and/or modify it
  under the terms of the GNU General Public License as published by the
  Free Software Foundation; either version 2, or (at your option) any
  later version.

  This program is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; see the file COPYING.  If not, write to the
  Free Software Foundation, Inc.,  675 Mass Ave, Cambridge, 
  MA 02139, USA.
*/
/*
 * Author: Stanko Kupcevic <kupcevic@redhat.com>
 */
/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.column_defines.conf,v 5.1 2002/05/08 05:42:47 hardaker Exp $
 */


#ifndef servicesMIB_columns_h
#define servicesMIB_columns_h

/*
 * column number definitions for table rhcServicesTable 
 */
#define COLUMN_RHCSERVICENAME		1
#define COLUMN_RHCSERVICESTATUSCODE		2
#define COLUMN_RHCSERVICESTATUSDESC		3
#define COLUMN_RHCSERVICESTARTMODE		4
#define COLUMN_RHCSERVICERUNNINGONNODE		5

#endif  // servicesMIB_columns_h
