#!/bin/bash
#
# qdiskd quorum disk daemon
#
# chkconfig: 345 22 78
# description: Starts and stops the quorum disk daemon

### BEGIN INIT INFO
# Provides: 		qdiskd
# Required-Start:	cman
# Required-Stop:	cman
# Default-Start:	3 4 5
# Default-Stop:		0 1 2 6
# Short-Description:	start/stop quorum disk daemon
# Description:		start/stop quorum disk daemon
### END INIT INFO

. /etc/init.d/functions
[ -f /etc/sysconfig/cluster ] && . /etc/sysconfig/cluster

LOCK_FILE="/var/lock/subsys/qdiskd"

rtrn=1
retries=0

# See how we were called.
case "$1" in
  start)
	echo -n "Starting the Quorum Disk Daemon:"

	$0 status >/dev/null
	if [ $? -eq 0 ]; then
		echo_success
		echo
		exit 0
	fi

	qdiskd -Q
	rtrn=$?
	if [ $rtrn = 0 ]; then
		touch $LOCK_FILE
		echo_success
		echo
	else
		echo_failure
		echo
	fi
		
	;;

  stop)
	echo -n "Stopping the Quorum Disk Daemon:"
	killproc qdiskd
	while [ -n "`pidof qdiskd`" ] && [ $retries -lt 5 ]; do
		sleep 1
		killproc qdiskd
		((retries++))
	done
	if [ -z "`pidof qdiskd`" ]; then
		echo_success
		echo
		rtrn=0
		rm -f $LOCK_FILE
	else
		echo_failure
		echo
		rtrn=1
	fi
	;;

  restart|reload)
	$0 stop || exit $?
	$0 start 
	rtrn=$?
	;;

  status)
	status qdiskd
	rtrn=$?
	;;

  *)
	echo $"Usage: $0 {start|stop|reload|restart|status}"
	;;
esac

exit $rtrn
