##############################################################################
###############################################################################
##
##  Copyright (C) Sistina Software, Inc.  1997-2003  All rights reserved.
##  Copyright (C) 2004-2006 Red Hat, Inc.  All rights reserved.
##  
##  This copyrighted material is made available to anyone wishing to use,
##  modify, copy, or redistribute it subject to the terms and conditions
##  of the GNU General Public License v.2.
##
###############################################################################
###############################################################################


all:
	cd apc && ${MAKE} all
	cd bladecenter && ${MAKE} all
	cd brocade && ${MAKE} all
	cd bullpap && ${MAKE} all
	# cd cpint && ${MAKE} all
	cd drac && ${MAKE} all
	cd egenera && ${MAKE} all
	# cd ibmblade && ${MAKE} all
	cd ilo && ${MAKE} all
	cd ipmilan && ${MAKE} all
	cd manual && ${MAKE} all
	cd mcdata && ${MAKE} all
	# cd rackswitch && ${MAKE} all
	cd rps10 && ${MAKE} all
	cd rsa && ${MAKE} all
	cd rsb && ${MAKE} all
	cd scsi && ${MAKE} all
	cd sanbox2 && ${MAKE} all
	cd vixel && ${MAKE} all
	cd wti && ${MAKE} all
	# cd xcat && ${MAKE} all
	# cd zvm && ${MAKE} all

copytobin:
	cd apc && ${MAKE} copytobin
	cd bladecenter && ${MAKE} copytobin
	cd brocade && ${MAKE} copytobin
	cd bullpap && ${MAKE} copytobin
	# cd cpint && ${MAKE} copytobin
	cd drac && ${MAKE} copytobin
	cd egenera && ${MAKE} copytobin
	# cd ibmblade && ${MAKE} copytobin
	cd ilo && ${MAKE} copytobin
	cd ipmilan && ${MAKE} copytobin
	cd manual && ${MAKE} copytobin
	cd mcdata && ${MAKE} copytobin
	# cd rackswitch && ${MAKE} copytobin
	cd rps10 && ${MAKE} copytobin
	cd rsa && ${MAKE} copytobin
	cd rsb && ${MAKE} copytobin
	cd scsi && ${MAKE} copytobin
	cd sanbox2 && ${MAKE} copytobin
	cd vixel && ${MAKE} copytobin
	cd wti && ${MAKE} copytobin
	# cd xcat && ${MAKE} copytobin
	# cd zvm && ${MAKE} copytobin

clean:
	cd apc && ${MAKE} clean
	cd bladecenter && ${MAKE} clean
	cd brocade && ${MAKE} clean
	cd bullpap && ${MAKE} clean
	#cd cpint && ${MAKE} clean
	cd drac && ${MAKE} clean
	cd egenera && ${MAKE} clean
	# cd ibmblade && ${MAKE} clean
	cd ilo && ${MAKE} clean
	cd ipmilan && ${MAKE} clean
	cd manual && ${MAKE} clean
	cd mcdata && ${MAKE} clean
	# cd rackswitch && ${MAKE} clean
	cd rps10 && ${MAKE} clean
	cd rsa && ${MAKE} clean
	cd rsb && ${MAKE} clean
	cd scsi && ${MAKE} clean
	cd sanbox2 && ${MAKE} clean
	cd vixel && ${MAKE} clean
	cd wti && ${MAKE} clean
	# cd xcat && ${MAKE} clean
	# cd zvm && ${MAKE} clean

