.TH "CLU_CONNECT" "3" "Mar 2004" "" "Magma Cluster Plugin Library"
.SH NAME
clu_connect, clu_disconnect \-
High-level cluster infrastructure connect/disconnect functions.
.SH SYNOPSIS
.nf
.B #include <magma.h>
.sp
.BI "int clu_connect(char *groupname, int login);"
.BI "int clu_disconnect(int fd);"
.BI "int cp_connect(cluster_plugin_t **cpp, char *groupname, int login);"
.fi
.SH DESCRIPTION
The \fBclu_connect()\fP function attempts to connect to the cluster
software running on the local machine.  If it successfully does so,
it registers for events and returns a file descriptor.
.LP
The returned file descriptor may be waited on using the \fBselect(2)\fP
system call.

The \fBclu_disconnect()\fP function cleans up all related descriptors,
threads, and other resources and unmaps the connected cluster plugin.
.SH "RETURN VALUE"
The \fBclu_connect()\fP function returns a file descriptor (>= 0) on success
or a negative value indicating the error incurred.
The \fBclu_disconnect()\fP function returns a file descriptor on success,
or -1 on failure.
.LP
The \fBclu_disconnect()\fP returns 0.
.SH "FILES"
.LP
/usr/lib/magma/* \- Cluster plugins.
.SH "SEE ALSO"
clu_get_event(3), select(2)
