.TH fence_ack_manual 8

.SH NAME
fence_ack_manual - program run by an operator as a part of manual I/O Fencing

.SH SYNOPSIS
.B
fence_ack_manual
[\fIOPTION\fR]...

.SH DESCRIPTION
fence_ack_manual is run by an operator on the same node that fence_manual(8) 
was run after the operator has reset a node which required fencing.  A message 
in the system log indicates to the operator that they must reset a machine and 
then run fence_ack_manual.  Running fence_ack_manual allows the cluster to 
continue with recovery of the fenced machine.  The victim may be disconnected 
from storage rather than resetting it.

.SH OPTIONS
.TP
\fB-h\fP
Print out a help message describing available options, then exit.
.TP
\fB-O\fP
Run without prompting for user confirmation.
.TP
\fB-n\fP \fInodename\fP
Name of node that has been reset or disconnected from storage.
.TP
\fB-s\fP \fIIPaddress\fP
IP address of the machine which has been reset or disconnected from storage.  (Deprecated; use -n instead.)
.TP
\fB-V\fP
Print out a version message, then exit.
.SH SEE ALSO
fence(8), fence_node(8)
