.TH fence_bullpap 8

.SH NAME
fence_bullpap - I/O Fencing agent for Bull FAME architecture controlled by a 
PAP management console.

.SH SYNOPSIS
.B
fence_bullpap
[\fIOPTION\fR]...

.SH DESCRIPTION
fence_bullpap is an I/O Fencing agent which can be used with Bull's NovaScale
machines controlled by PAP management consoles.  This agent calls Bull's
support software provided by the NSMasterHW RPM available from Bull.

fence_bullpap accepts options on the command line as well as from stdin.  
fenced sends the options through stdin when it execs the agent.  fence_bullpap
can be run by itself with command line options which is useful for testing.

.SH OPTIONS
.TP
\fB-a\fP \fIIPaddress\fP
IP address or hostname of the PAP management console.
.TP
\fB-h\fP
Print out a help message describing available options, then exit.
.TP
\fB-l\fP \fIlogin\fP
Login with administrative privileges.
.TP
\fB-d\fP \fIdomain\fP
This is the domain name of the Bull machine to power-cycle.
.TP
\fB-o\fP \fIoption\fP
Action to perform (on, off, reboot, status).
.TP
\fB-p\fP \fIpassword\fP
Password for login.
.TP
\fB-S\fP \fIpath\fR
Full path to an executable to generate the password for login.
.TP
\fB-q\fP
Quiet operation.  Only print out error messages.
.TP
\fB-V\fP
Print out a version message, then exit.

.SH STDIN PARAMETERS
.TP
\fIipaddr = < hostname | ip >\fR
IP address or hostname of the PAP management console.
.TP
\fIlogin= < param >\fR
Login with administrative privileges.
.TP
\fIdomain = < param >\fR
This is the domain name of the Bull machine to power-cycle.
.TP
\fIoption = < param >\fR
Action to perform (on, off, reboot, status).
.TP
\fIpasswd = < param >\fR
Password for login.
.TP
\fIpasswd_script = < param >\fR
Full path to an executable to generate the password for login.

.SH SEE ALSO
fence(8), fence_node(8)
