.TH fence_node 8

.SH NAME
fence_node - A program which performs I/O fencing on a single node.

.SH SYNOPSIS
.B
fence_node
[\fIOPTION\fR]...

.SH DESCRIPTION
\fBfence_node\fP is a program that reads the fencing settings from
cluster.conf (through libccs/ccsd) for the given node and then runs the
configured fencing agent against the node.

.SH OPTIONS
.TP
\fB-h\fP
Help.  Print out the usage syntax.
.TP
\fB-O\fP
Force a connection to CCS.  This overrides the usual
requirement that the cluster be quorate to get information from ccs.
.TP
\fB-V\fP
Print version information.

.SH EXAMPLES
.TP
To fence a node called ``bellerophon'':
prompt> fence_node bellerophon

.SH SEE ALSO
fence(8), ccs(7)
