.TH fence_tool 8

.SH NAME
fence_tool - A program to join and leave the fence domain

.SH SYNOPSIS
.B
fence_tool
<\fBjoin | leave | ls | dump\fP> 
[\fIOPTION\fR]...

.SH DESCRIPTION
\fBfence_tool\fP is a program used to join or leave the default fence
domain.  It communicates with the fenced daemon.  Before telling fenced
to join the domain, fence_tool waits for the cluster to have quorum,
making it easier to cancel the command if the cluster is inquorate.

The dump option will read fenced's ring buffer of debug messages and print
it to stdout.

.SH OPTIONS
.TP
\fB-m\fP <n>
Delay join up to n seconds for all nodes in cluster.conf to be cluster members.
.TP
\fB-w\fP
Wait until the join or leave is completed.
.TP
\fB-h\fP
Help.  Print out the usage syntax.
.TP
\fB-V\fP
Print version information.
.TP
\fB-t\fP <n>
Maximum time in seconds to wait for quorum or -w (default: 300 seconds)
.TP
\fB-Q\fP
Fail command immediately if the cluster is not quorate, don't wait.

.SH SEE ALSO
fenced(8), fence(8), fence_node(8)
