.TH fence_mcdata 8

.SH NAME
fence_mcdata - I/O Fencing agent for McData FC switches

.SH SYNOPSIS
.B
fence_mcdata
[\fIOPTION\fR]...

.SH DESCRIPTION
fence_mcdata is an I/O Fencing agent which can be used with McData FC 
switches.  It logs into a McData switch via telnet and disables a specified 
port.  Disabling the port which a machine is connected to effectively fences 
that machine.  Lengthy telnet connections to the switch should be avoided 
while a GFS cluster is running because the connection will block any necessary 
fencing actions.

fence_mcdata accepts options on the command line as well as from stdin.
fenced sends parameters through stdin when it execs the agent.  fence_mcdata 
can be run by itself with command line options which is useful for testing.

After a fence operation has taken place the fenced machine can no longer connect
to the McData FC switch.  When the fenced machine is ready to be brought back 
into the GFS cluster (after reboot) the port on the McData FC switch needs to 
be enabled. This can be done by running fence_mcdata and specifying the 
enable action.

.SH OPTIONS
.TP
\fB-a\fP \fIIPaddress\fP
IP address of the switch.
.TP
\fB-h\fP
Print out a help message describing available options, then exit.
.TP
\fB-l\fP \fIlogin\fP
Username name for the switch.
.TP
\fB-n\fP \fIport\fP
The port number to disable on the switch.
.TP
\fB-o\fP \fIaction\fP
The action required.  disable (default) or enable.
.TP
\fB-p\fP \fIpassword\fP
Password for login.
.TP
\fB-S\fP \fIpath\fR
Full path to an executable to generate the password for login.
.TP
\fB-q\fP
Quiet mode: print only error messages.
.TP
\fB-V\fP
Print out a version message, then exit.

.SH STDIN PARAMETERS
.TP
\fIagent = < param >\fR
This option is used by fence_node(8) and is ignored by fence_mcdata.
.TP
\fIipaddr = < hostname | ip >\fR
IP address or hostname of the switch.
.TP
\fIlogin = < param >\fR
Login name.
.TP
\fIoption = < param >\fR
The action required.  disable (default) or enable.
.TP
\fIpasswd = < param >\fR
Password for login.
.TP
\fIpasswd_script = < param >\fR
Full path to an executable to generate the password for login.
.TP
\fIport = < param >\fR
The port number to disable on the switch.

.SH SEE ALSO
fence(8), fence_node(8)
