.\"  Copyright (C) Sistina Software, Inc.  1997-2003  All rights reserved.
.\"  Copyright (C) 2004 Red Hat, Inc.  All rights reserved.
.\"  
.\"  This copyrighted material is made available to anyone wishing to use,
.\"  modify, copy, or redistribute it subject to the terms and conditions
.\"  of the GNU General Public License v.2.

.TH fence 8

.SH NAME
I/O Fencing reference guide

.SH SYNOPSIS
Overview of related manual pages
.SH DESCRIPTION
The I/O Fencing documentation has been split into a number of sections.  Please
refer to the table below to determine which man page coincides with the
command/feature you are looking for.

.TP 20
fence
I/O Fencing overview (this man page)
.TP
fenced
I/O Fencing daemon
.TP
fence_tool
Manages fenced
.TP
fence_node
Calls the fence agent specified in the configuration file

.SS I/O Fencing agents

.TP 20
fence_apc
for APC MasterSwitch and APC 79xx models
.TP
fence_bladecenter
for IBM Bladecenters w/ telnet interface
.TP
fence_brocade
for Brocade fibre channel switches (PortDisable)
.TP
fence_egenera
for Egenera blades
.TP
fence_gnbd
for GNBD-based GFS clusters
.TP
fence_ilo
for HP ILO interfaces (formerly fence_rib)
.TP
fence_manual
for manual intervention
.TP
fence_mcdata
for McData fibre channel switches
.TP
fence_ack_manual
for manual intervention
.TP
fence_sanbox2
for Qlogic SAN Box fibre channel switches
.TP
fence_vixel
for Vixel switches (PortDisable)
.TP
fence_wti
for WTI Network Power Switch

.SH SEE ALSO
gnbd(8), gfs(8)
