.TH fence_ibmblade 8

.SH NAME
fence_ibmblade - I/O Fencing agent for IBM BladeCenter 

.SH SYNOPSIS
.B
fence_ibmblade
[\fIOPTION\fR]...

.SH DESCRIPTION
fence_ibmblade is an I/O Fencing agent which can be used with IBM BladeCenter 
chassis. It issues SNMP Set request to BladeCenter chassis, rebooting, powering
up or down the specified Blade Server. 

fence_ibmblade accepts options on the command line as well as from stdin.
fenced sends parameters through stdin when it execs the agent.  fence_ibmblade 
can be run by itself with command line options which is useful for testing.

.SH OPTIONS
.TP
\fB-a\fP \fIIPaddress\fP
IP address of the BladeCenter chassis. 
.TP
\fB-h\fP
Print out a help message describing available options, then exit.
.TP
\fB-c\fP \fIcommunity\fP
SNMP community string to use.
.TP
\fB-n\fP \fIport\fP
The Blade port number to disable.
.TP
\fB-o\fP \fIaction\fP
The action required.  This can be reboot (default), on or off.
.TP
\fB-q\fP
Quiet mode: print only error messages.
.TP
\fB-V\fP
Print out a version message, then exit.

.SH STDIN PARAMETERS
.TP
\fIagent = < param >\fR
This option is used by fence_node(8) and is ignored by fence_ibmblade.
.TP
\fIipaddr = < hostname | ip >\fR
IP address or hostname of the switch.
.TP
\fIcommunity = < param >\fR
SNMP community.
.TP
\fIoption = < param >\fR
The action required.  reboot (default), on or off.
.TP
\fIport = < param >\fR
The Blade port number to disable.

.SH SEE ALSO
fence(8), fence_node(8)
