TARGET= fence.8 \
	fence_ack_manual.8 \
	fence_alom.8 \
	fence_apc.8 \
	fence_rsa.8 \
	fence_bladecenter.8 \
	fence_brocade.8 \
	fence_drac.8 \
	fence_egenera.8 \
	fence_eps.8 \
	fence_gnbd.8 \
	fence_ifmib.8 \
	fence_ilo.8 \
	fence_ldom.8 \
	fence_manual.8 \
	fence_mcdata.8 \
	fence_node.8 \
	fence_rib.8 \
	fence_sanbox2.8 \
	fence_tool.8 \
	fence_vixel.8 \
	fence_wti.8 \
	fence_bullpap.8 \
	fence_ipmilan.8 \
	fence_vmware.8 \
	fence_vmware_vmrun.8 \
	fence_xvm.8 \
	fence_xvmd.8 \
	fenced.8

include ../../make/defines.mk
include $(OBJDIR)/make/man.mk
