include ../../../make/defines.mk

PMTARGET = CCS.pm

TARGET = $(PMTARGET)

CFLAGS += -I${ccsincdir}
CFLAGS += -I${incdir}

LDFLAGS += -L${ccslibdir} -lccs
LDFLAGS += -L${libdir}

include $(OBJDIR)/make/perl-binding-common.mk
