.TH groupd 8

.SH NAME
groupd - the group manager for fenced, dlm_controld and gfs_controld

.SH SYNOPSIS
.B
groupd
[\fIOPTION\fR]...

.SH DESCRIPTION

The group daemon, groupd, provides a compatibility layer between the
openais closed process group (CPG) service and the fenced, dlm_controld
and gfs_controld daemons.  groupd and its associated libgroup interface
will go away in the future as the fencing, dlm and gfs daemons are ported
to use the libcpg interfaces directly.  groupd translates and buffers cpg
events between openais's cpg service and the fence/dlm/gfs systems that
use it.  CPG's are used to represent the membership of the fence domain,
dlm lockspaces and gfs mount groups.

groupd is also a convenient place to query the status of the fence, dlm
and gfs groups.  This is done by the group_tool program.


.SH OPTIONS
.TP
\fB-D\fP
Run the daemon in the foreground and print debug statements to stdout.
.TP
\fB-V\fP
Print the version information and exit.
.TP
\fB-h\fP 
Print out a help message describing available options, then exit.

.SH DEBUGGING
The groupd daemon keeps a circular buffer of debug messages that can be
dumped with the 'group_tool dump' command.

.SH SEE ALSO
group_tool(8)

