.TH group_tool 8

.SH NAME
group_tool - display/dump information about fence, dlm and gfs groups

.SH SYNOPSIS
.B
group_tool
[\fISUBCOMMAND\fR] [\fIOPTION\fR]...

.SH DESCRIPTION

The group_tool program displays the status of fence, dlm and gfs groups.
The information is read from the groupd daemon which controls the fenced,
dlm_controld and gfs_controld daemons.  group_tool will also dump debug
logs from various daemons.

.SH SUBCOMMANDS

.TP
\fBls\fP
displays the list of groups and their membership.  It is the default
subcommand if none is specified.

.TP
\fBdump\fP
dumps the debug log from groupd.

.TP
\fBdump fence\fP
dumps the debug log from fenced.

.TP
\fBdump gfs\fP
dumps the debug log from gfs_controld.

.TP
\fBdump plocks\fP <fsname>
prints the posix locks on the named gfs fs from gfs_controld.

.SH OPTIONS
.TP
\fB-v\fP
Verbose output, used with the 'ls' subcommand.
.TP
\fB-D\fP
Run the daemon in the foreground and print debug statements to stdout.
.TP
\fB-V\fP
Print the version information and exit.
.TP
\fB-h\fP 
Print out a help message describing available options, then exit.

.SH DEBUGGING
The groupd daemon keeps a circular buffer of debug messages that can be
dumped with the 'group_tool dump' command.

.SH SEE ALSO
groupd(8)

