###############################################################################
###############################################################################
##
##  Copyright (C) 2007 Red Hat, Inc.  All rights reserved.
##
##  This copyrighted material is made available to anyone wishing to use,
##  modify, copy, or redistribute it subject to the terms and conditions
##  of the GNU General Public License v.2.
##
###############################################################################
###############################################################################

TARGET= dlm_controld.8 \
	gfs_controld.8 \
	group_tool.8 \
	groupd.8

include ../../make/defines.mk
include $(OBJDIR)/make/man.mk
