.TH OCF-TESTER "8" "January 2012" "Tool for testing if a cluster resource is OCF compliant" "System Administration Utilities"
.SH NAME
ocf-tester \- Part of the Linux-HA project
.SH SYNOPSIS
.B ocf-tester
[\fI-Lh\fR] \fI-n resource_name \fR[\fI-o name=value\fR]\fI* /full/path/to/resource/agent\fR
.SH DESCRIPTION
Tool for testing if a cluster resource is OCF compliant
.SH OPTIONS
.TP
\fB\-h\fR
This text
.TP
\fB\-v\fR
Be verbose while testing
.TP
\fB\-q\fR
Be quiet while testing
.TP
\fB\-d\fR
Turn on RA debugging
.TP
\fB\-n\fR name
Name of the resource
.TP
\fB\-o\fR name=value
Name and value of any parameters required by the agent
.TP
\fB\-L\fR
Use lrmadmin/lrmd for tests
.PP
Usage: ocf\-tester [\-Lh] \fB\-n\fR resource_name [\-o name=value]* /full/path/to/resource/agent
.TP
\fB\-h\fR
This text
.TP
\fB\-v\fR
Be verbose while testing
.TP
\fB\-q\fR
Be quiet while testing
.TP
\fB\-d\fR
Turn on RA debugging
.TP
\fB\-n\fR name
Name of the resource
.TP
\fB\-o\fR name=value
Name and value of any parameters required by the agent
.TP
\fB\-L\fR
Use lrmadmin/lrmd for tests
